/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.tsp.gespro.dto;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

/** 
 * This class represents the primary key of the topic table.
 */
public class TopicPk implements Serializable
{
	protected long idTopic;

	/** 
	 * This attribute represents whether the primitive attribute idTopic is null.
	 */
	protected boolean idTopicNull;

	/** 
	 * Sets the value of idTopic
	 */
	public void setIdTopic(long idTopic)
	{
		this.idTopic = idTopic;
	}

	/** 
	 * Gets the value of idTopic
	 */
	public long getIdTopic()
	{
		return idTopic;
	}

	/**
	 * Method 'TopicPk'
	 * 
	 */
	public TopicPk()
	{
	}

	/**
	 * Method 'TopicPk'
	 * 
	 * @param idTopic
	 */
	public TopicPk(final long idTopic)
	{
		this.idTopic = idTopic;
	}

	/** 
	 * Sets the value of idTopicNull
	 */
	public void setIdTopicNull(boolean idTopicNull)
	{
		this.idTopicNull = idTopicNull;
	}

	/** 
	 * Gets the value of idTopicNull
	 */
	public boolean isIdTopicNull()
	{
		return idTopicNull;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof TopicPk)) {
			return false;
		}
		
		final TopicPk _cast = (TopicPk) _other;
		if (idTopic != _cast.idTopic) {
			return false;
		}
		
		if (idTopicNull != _cast.idTopicNull) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		_hashCode = 29 * _hashCode + (int) (idTopic ^ (idTopic >>> 32));
		_hashCode = 29 * _hashCode + (idTopicNull ? 1 : 0);
		return _hashCode;
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "com.tsp.gespro.dto.TopicPk: " );
		ret.append( "idTopic=" + idTopic );
		return ret.toString();
	}

}
