package com.tsp.gespro.hibernate.pojo;
// Generated 1/08/2016 04:33:46 AM by Hibernate Tools 4.3.1



/**
 * CampoAdicionalSucursalValor generated by hbm2java
 */
public class CampoAdicionalSucursalValor  implements java.io.Serializable {


     private int idCampoAdicionalSucursalValor;
     private CampoAdicionalSucursal campoAdicionalSucursal;
     private String valor;
     private Integer idSucursal;

    public CampoAdicionalSucursalValor() {
    }

	
    public CampoAdicionalSucursalValor(int idCampoAdicionalSucursalValor) {
        this.idCampoAdicionalSucursalValor = idCampoAdicionalSucursalValor;
    }
    public CampoAdicionalSucursalValor(int idCampoAdicionalSucursalValor, CampoAdicionalSucursal campoAdicionalSucursal, String valor, Integer idSucursal) {
       this.idCampoAdicionalSucursalValor = idCampoAdicionalSucursalValor;
       this.campoAdicionalSucursal = campoAdicionalSucursal;
       this.valor = valor;
       this.idSucursal = idSucursal;
    }
   
    public int getIdCampoAdicionalSucursalValor() {
        return this.idCampoAdicionalSucursalValor;
    }
    
    public void setIdCampoAdicionalSucursalValor(int idCampoAdicionalSucursalValor) {
        this.idCampoAdicionalSucursalValor = idCampoAdicionalSucursalValor;
    }
    public CampoAdicionalSucursal getCampoAdicionalSucursal() {
        return this.campoAdicionalSucursal;
    }
    
    public void setCampoAdicionalSucursal(CampoAdicionalSucursal campoAdicionalSucursal) {
        this.campoAdicionalSucursal = campoAdicionalSucursal;
    }
    public String getValor() {
        return this.valor;
    }
    
    public void setValor(String valor) {
        this.valor = valor;
    }
    public Integer getIdSucursal() {
        return this.idSucursal;
    }
    
    public void setIdSucursal(Integer idSucursal) {
        this.idSucursal = idSucursal;
    }




}


