package com.tsp.gespro.hibernate.pojo;
// Generated 28/08/2016 01:00:35 AM by Hibernate Tools 3.2.1.GA



/**
 * ClientesClientes generated by hbm2java
 */
public class ClientesClientes  implements java.io.Serializable {


     private int id;
     private Integer clienteId;
     private Integer clienteSucursalId;

    public ClientesClientes() {
    }

	
    public ClientesClientes(int id) {
        this.id = id;
    }
    public ClientesClientes(int id, Integer clienteId, Integer clienteSucursalId) {
       this.id = id;
       this.clienteId = clienteId;
       this.clienteSucursalId = clienteSucursalId;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Integer getClienteId() {
        return this.clienteId;
    }
    
    public void setClienteId(Integer clienteId) {
        this.clienteId = clienteId;
    }
    public Integer getClienteSucursalId() {
        return this.clienteSucursalId;
    }
    
    public void setClienteSucursalId(Integer clienteSucursalId) {
        this.clienteSucursalId = clienteSucursalId;
    }




}


