package com.tsp.gespro.hibernate.pojo;
// Generated 19/08/2016 06:34:39 PM by Hibernate Tools 3.6.0



/**
 * Cobertura generated by hbm2java
 */
public class Cobertura  implements java.io.Serializable {


     private Integer idCobertura;
     private String nombre;

    public Cobertura() {
    }

    public Cobertura(String nombre) {
       this.nombre = nombre;
    }
   
    public Integer getIdCobertura() {
        return this.idCobertura;
    }
    
    public void setIdCobertura(Integer idCobertura) {
        this.idCobertura = idCobertura;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }




}


