/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.tsp.gespro.dto;

import com.tsp.gespro.dao.*;
import com.tsp.gespro.factory.*;
import com.tsp.gespro.exceptions.*;
import java.io.Serializable;
import java.util.*;
import java.util.Date;

public class DetalleHorario implements Serializable
{
	/** 
	 * This attribute maps to the column ID_DETALLE_HORARIO in the detalle_horario table.
	 */
	protected int idDetalleHorario;

	/** 
	 * This attribute represents whether the attribute idDetalleHorario has been modified since being read from the database.
	 */
	protected boolean idDetalleHorarioModified = false;

	/** 
	 * This attribute maps to the column ID_HORARIO in the detalle_horario table.
	 */
	protected int idHorario;

	/** 
	 * This attribute represents whether the attribute idHorario has been modified since being read from the database.
	 */
	protected boolean idHorarioModified = false;

	/** 
	 * This attribute maps to the column DIA in the detalle_horario table.
	 */
	protected String dia;

	/** 
	 * This attribute represents whether the attribute dia has been modified since being read from the database.
	 */
	protected boolean diaModified = false;

	/** 
	 * This attribute maps to the column HORA_ENTRADA in the detalle_horario table.
	 */
	protected Date horaEntrada;

	/** 
	 * This attribute represents whether the attribute horaEntrada has been modified since being read from the database.
	 */
	protected boolean horaEntradaModified = false;

	/** 
	 * This attribute maps to the column HORA_SALIDA in the detalle_horario table.
	 */
	protected Date horaSalida;

	/** 
	 * This attribute represents whether the attribute horaSalida has been modified since being read from the database.
	 */
	protected boolean horaSalidaModified = false;

	/** 
	 * This attribute maps to the column DIA_DESCANSO in the detalle_horario table.
	 */
	protected int diaDescanso;

	/** 
	 * This attribute represents whether the primitive attribute diaDescanso is null.
	 */
	protected boolean diaDescansoNull = true;

	/** 
	 * This attribute represents whether the attribute diaDescanso has been modified since being read from the database.
	 */
	protected boolean diaDescansoModified = false;

	/** 
	 * This attribute maps to the column COMIDA_SALIDA in the detalle_horario table.
	 */
	protected Date comidaSalida;

	/** 
	 * This attribute represents whether the attribute comidaSalida has been modified since being read from the database.
	 */
	protected boolean comidaSalidaModified = false;

	/** 
	 * This attribute maps to the column COMIDA_ENTRADA in the detalle_horario table.
	 */
	protected Date comidaEntrada;

	/** 
	 * This attribute represents whether the attribute comidaEntrada has been modified since being read from the database.
	 */
	protected boolean comidaEntradaModified = false;

	/** 
	 * This attribute maps to the column PERIODO_COMIDA in the detalle_horario table.
	 */
	protected int periodoComida;

	/** 
	 * This attribute represents whether the primitive attribute periodoComida is null.
	 */
	protected boolean periodoComidaNull = true;

	/** 
	 * This attribute represents whether the attribute periodoComida has been modified since being read from the database.
	 */
	protected boolean periodoComidaModified = false;

	/** 
	 * This attribute maps to the column TOLERANCIA in the detalle_horario table.
	 */
	protected int tolerancia;

	/** 
	 * This attribute represents whether the primitive attribute tolerancia is null.
	 */
	protected boolean toleranciaNull = true;

	/** 
	 * This attribute represents whether the attribute tolerancia has been modified since being read from the database.
	 */
	protected boolean toleranciaModified = false;

	/**
	 * Method 'DetalleHorario'
	 * 
	 */
	public DetalleHorario()
	{
	}

	/**
	 * Method 'getIdDetalleHorario'
	 * 
	 * @return int
	 */
	public int getIdDetalleHorario()
	{
		return idDetalleHorario;
	}

	/**
	 * Method 'setIdDetalleHorario'
	 * 
	 * @param idDetalleHorario
	 */
	public void setIdDetalleHorario(int idDetalleHorario)
	{
		this.idDetalleHorario = idDetalleHorario;
		this.idDetalleHorarioModified = true;
	}

	/** 
	 * Sets the value of idDetalleHorarioModified
	 */
	public void setIdDetalleHorarioModified(boolean idDetalleHorarioModified)
	{
		this.idDetalleHorarioModified = idDetalleHorarioModified;
	}

	/** 
	 * Gets the value of idDetalleHorarioModified
	 */
	public boolean isIdDetalleHorarioModified()
	{
		return idDetalleHorarioModified;
	}

	/**
	 * Method 'getIdHorario'
	 * 
	 * @return int
	 */
	public int getIdHorario()
	{
		return idHorario;
	}

	/**
	 * Method 'setIdHorario'
	 * 
	 * @param idHorario
	 */
	public void setIdHorario(int idHorario)
	{
		this.idHorario = idHorario;
		this.idHorarioModified = true;
	}

	/** 
	 * Sets the value of idHorarioModified
	 */
	public void setIdHorarioModified(boolean idHorarioModified)
	{
		this.idHorarioModified = idHorarioModified;
	}

	/** 
	 * Gets the value of idHorarioModified
	 */
	public boolean isIdHorarioModified()
	{
		return idHorarioModified;
	}

	/**
	 * Method 'getDia'
	 * 
	 * @return String
	 */
	public String getDia()
	{
		return dia;
	}

	/**
	 * Method 'setDia'
	 * 
	 * @param dia
	 */
	public void setDia(String dia)
	{
		this.dia = dia;
		this.diaModified = true;
	}

	/** 
	 * Sets the value of diaModified
	 */
	public void setDiaModified(boolean diaModified)
	{
		this.diaModified = diaModified;
	}

	/** 
	 * Gets the value of diaModified
	 */
	public boolean isDiaModified()
	{
		return diaModified;
	}

	/**
	 * Method 'getHoraEntrada'
	 * 
	 * @return Date
	 */
	public Date getHoraEntrada()
	{
		return horaEntrada;
	}

	/**
	 * Method 'setHoraEntrada'
	 * 
	 * @param horaEntrada
	 */
	public void setHoraEntrada(Date horaEntrada)
	{
		this.horaEntrada = horaEntrada;
		this.horaEntradaModified = true;
	}

	/** 
	 * Sets the value of horaEntradaModified
	 */
	public void setHoraEntradaModified(boolean horaEntradaModified)
	{
		this.horaEntradaModified = horaEntradaModified;
	}

	/** 
	 * Gets the value of horaEntradaModified
	 */
	public boolean isHoraEntradaModified()
	{
		return horaEntradaModified;
	}

	/**
	 * Method 'getHoraSalida'
	 * 
	 * @return Date
	 */
	public Date getHoraSalida()
	{
		return horaSalida;
	}

	/**
	 * Method 'setHoraSalida'
	 * 
	 * @param horaSalida
	 */
	public void setHoraSalida(Date horaSalida)
	{
		this.horaSalida = horaSalida;
		this.horaSalidaModified = true;
	}

	/** 
	 * Sets the value of horaSalidaModified
	 */
	public void setHoraSalidaModified(boolean horaSalidaModified)
	{
		this.horaSalidaModified = horaSalidaModified;
	}

	/** 
	 * Gets the value of horaSalidaModified
	 */
	public boolean isHoraSalidaModified()
	{
		return horaSalidaModified;
	}

	/**
	 * Method 'getDiaDescanso'
	 * 
	 * @return int
	 */
	public int getDiaDescanso()
	{
		return diaDescanso;
	}

	/**
	 * Method 'setDiaDescanso'
	 * 
	 * @param diaDescanso
	 */
	public void setDiaDescanso(int diaDescanso)
	{
		this.diaDescanso = diaDescanso;
		this.diaDescansoNull = false;
		this.diaDescansoModified = true;
	}

	/**
	 * Method 'setDiaDescansoNull'
	 * 
	 * @param value
	 */
	public void setDiaDescansoNull(boolean value)
	{
		this.diaDescansoNull = value;
		this.diaDescansoModified = true;
	}

	/**
	 * Method 'isDiaDescansoNull'
	 * 
	 * @return boolean
	 */
	public boolean isDiaDescansoNull()
	{
		return diaDescansoNull;
	}

	/** 
	 * Sets the value of diaDescansoModified
	 */
	public void setDiaDescansoModified(boolean diaDescansoModified)
	{
		this.diaDescansoModified = diaDescansoModified;
	}

	/** 
	 * Gets the value of diaDescansoModified
	 */
	public boolean isDiaDescansoModified()
	{
		return diaDescansoModified;
	}

	/**
	 * Method 'getComidaSalida'
	 * 
	 * @return Date
	 */
	public Date getComidaSalida()
	{
		return comidaSalida;
	}

	/**
	 * Method 'setComidaSalida'
	 * 
	 * @param comidaSalida
	 */
	public void setComidaSalida(Date comidaSalida)
	{
		this.comidaSalida = comidaSalida;
		this.comidaSalidaModified = true;
	}

	/** 
	 * Sets the value of comidaSalidaModified
	 */
	public void setComidaSalidaModified(boolean comidaSalidaModified)
	{
		this.comidaSalidaModified = comidaSalidaModified;
	}

	/** 
	 * Gets the value of comidaSalidaModified
	 */
	public boolean isComidaSalidaModified()
	{
		return comidaSalidaModified;
	}

	/**
	 * Method 'getComidaEntrada'
	 * 
	 * @return Date
	 */
	public Date getComidaEntrada()
	{
		return comidaEntrada;
	}

	/**
	 * Method 'setComidaEntrada'
	 * 
	 * @param comidaEntrada
	 */
	public void setComidaEntrada(Date comidaEntrada)
	{
		this.comidaEntrada = comidaEntrada;
		this.comidaEntradaModified = true;
	}

	/** 
	 * Sets the value of comidaEntradaModified
	 */
	public void setComidaEntradaModified(boolean comidaEntradaModified)
	{
		this.comidaEntradaModified = comidaEntradaModified;
	}

	/** 
	 * Gets the value of comidaEntradaModified
	 */
	public boolean isComidaEntradaModified()
	{
		return comidaEntradaModified;
	}

	/**
	 * Method 'getPeriodoComida'
	 * 
	 * @return int
	 */
	public int getPeriodoComida()
	{
		return periodoComida;
	}

	/**
	 * Method 'setPeriodoComida'
	 * 
	 * @param periodoComida
	 */
	public void setPeriodoComida(int periodoComida)
	{
		this.periodoComida = periodoComida;
		this.periodoComidaNull = false;
		this.periodoComidaModified = true;
	}

	/**
	 * Method 'setPeriodoComidaNull'
	 * 
	 * @param value
	 */
	public void setPeriodoComidaNull(boolean value)
	{
		this.periodoComidaNull = value;
		this.periodoComidaModified = true;
	}

	/**
	 * Method 'isPeriodoComidaNull'
	 * 
	 * @return boolean
	 */
	public boolean isPeriodoComidaNull()
	{
		return periodoComidaNull;
	}

	/** 
	 * Sets the value of periodoComidaModified
	 */
	public void setPeriodoComidaModified(boolean periodoComidaModified)
	{
		this.periodoComidaModified = periodoComidaModified;
	}

	/** 
	 * Gets the value of periodoComidaModified
	 */
	public boolean isPeriodoComidaModified()
	{
		return periodoComidaModified;
	}

	/**
	 * Method 'getTolerancia'
	 * 
	 * @return int
	 */
	public int getTolerancia()
	{
		return tolerancia;
	}

	/**
	 * Method 'setTolerancia'
	 * 
	 * @param tolerancia
	 */
	public void setTolerancia(int tolerancia)
	{
		this.tolerancia = tolerancia;
		this.toleranciaNull = false;
		this.toleranciaModified = true;
	}

	/**
	 * Method 'setToleranciaNull'
	 * 
	 * @param value
	 */
	public void setToleranciaNull(boolean value)
	{
		this.toleranciaNull = value;
		this.toleranciaModified = true;
	}

	/**
	 * Method 'isToleranciaNull'
	 * 
	 * @return boolean
	 */
	public boolean isToleranciaNull()
	{
		return toleranciaNull;
	}

	/** 
	 * Sets the value of toleranciaModified
	 */
	public void setToleranciaModified(boolean toleranciaModified)
	{
		this.toleranciaModified = toleranciaModified;
	}

	/** 
	 * Gets the value of toleranciaModified
	 */
	public boolean isToleranciaModified()
	{
		return toleranciaModified;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof DetalleHorario)) {
			return false;
		}
		
		final DetalleHorario _cast = (DetalleHorario) _other;
		if (idDetalleHorario != _cast.idDetalleHorario) {
			return false;
		}
		
		if (idDetalleHorarioModified != _cast.idDetalleHorarioModified) {
			return false;
		}
		
		if (idHorario != _cast.idHorario) {
			return false;
		}
		
		if (idHorarioModified != _cast.idHorarioModified) {
			return false;
		}
		
		if (dia == null ? _cast.dia != dia : !dia.equals( _cast.dia )) {
			return false;
		}
		
		if (diaModified != _cast.diaModified) {
			return false;
		}
		
		if (horaEntrada == null ? _cast.horaEntrada != horaEntrada : !horaEntrada.equals( _cast.horaEntrada )) {
			return false;
		}
		
		if (horaEntradaModified != _cast.horaEntradaModified) {
			return false;
		}
		
		if (horaSalida == null ? _cast.horaSalida != horaSalida : !horaSalida.equals( _cast.horaSalida )) {
			return false;
		}
		
		if (horaSalidaModified != _cast.horaSalidaModified) {
			return false;
		}
		
		if (diaDescanso != _cast.diaDescanso) {
			return false;
		}
		
		if (diaDescansoNull != _cast.diaDescansoNull) {
			return false;
		}
		
		if (diaDescansoModified != _cast.diaDescansoModified) {
			return false;
		}
		
		if (comidaSalida == null ? _cast.comidaSalida != comidaSalida : !comidaSalida.equals( _cast.comidaSalida )) {
			return false;
		}
		
		if (comidaSalidaModified != _cast.comidaSalidaModified) {
			return false;
		}
		
		if (comidaEntrada == null ? _cast.comidaEntrada != comidaEntrada : !comidaEntrada.equals( _cast.comidaEntrada )) {
			return false;
		}
		
		if (comidaEntradaModified != _cast.comidaEntradaModified) {
			return false;
		}
		
		if (periodoComida != _cast.periodoComida) {
			return false;
		}
		
		if (periodoComidaNull != _cast.periodoComidaNull) {
			return false;
		}
		
		if (periodoComidaModified != _cast.periodoComidaModified) {
			return false;
		}
		
		if (tolerancia != _cast.tolerancia) {
			return false;
		}
		
		if (toleranciaNull != _cast.toleranciaNull) {
			return false;
		}
		
		if (toleranciaModified != _cast.toleranciaModified) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		_hashCode = 29 * _hashCode + idDetalleHorario;
		_hashCode = 29 * _hashCode + (idDetalleHorarioModified ? 1 : 0);
		_hashCode = 29 * _hashCode + idHorario;
		_hashCode = 29 * _hashCode + (idHorarioModified ? 1 : 0);
		if (dia != null) {
			_hashCode = 29 * _hashCode + dia.hashCode();
		}
		
		_hashCode = 29 * _hashCode + (diaModified ? 1 : 0);
		if (horaEntrada != null) {
			_hashCode = 29 * _hashCode + horaEntrada.hashCode();
		}
		
		_hashCode = 29 * _hashCode + (horaEntradaModified ? 1 : 0);
		if (horaSalida != null) {
			_hashCode = 29 * _hashCode + horaSalida.hashCode();
		}
		
		_hashCode = 29 * _hashCode + (horaSalidaModified ? 1 : 0);
		_hashCode = 29 * _hashCode + diaDescanso;
		_hashCode = 29 * _hashCode + (diaDescansoNull ? 1 : 0);
		_hashCode = 29 * _hashCode + (diaDescansoModified ? 1 : 0);
		if (comidaSalida != null) {
			_hashCode = 29 * _hashCode + comidaSalida.hashCode();
		}
		
		_hashCode = 29 * _hashCode + (comidaSalidaModified ? 1 : 0);
		if (comidaEntrada != null) {
			_hashCode = 29 * _hashCode + comidaEntrada.hashCode();
		}
		
		_hashCode = 29 * _hashCode + (comidaEntradaModified ? 1 : 0);
		_hashCode = 29 * _hashCode + periodoComida;
		_hashCode = 29 * _hashCode + (periodoComidaNull ? 1 : 0);
		_hashCode = 29 * _hashCode + (periodoComidaModified ? 1 : 0);
		_hashCode = 29 * _hashCode + tolerancia;
		_hashCode = 29 * _hashCode + (toleranciaNull ? 1 : 0);
		_hashCode = 29 * _hashCode + (toleranciaModified ? 1 : 0);
		return _hashCode;
	}

	/**
	 * Method 'createPk'
	 * 
	 * @return DetalleHorarioPk
	 */
	public DetalleHorarioPk createPk()
	{
		return new DetalleHorarioPk(idDetalleHorario);
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "com.tsp.gespro.dto.DetalleHorario: " );
		ret.append( "idDetalleHorario=" + idDetalleHorario );
		ret.append( ", idHorario=" + idHorario );
		ret.append( ", dia=" + dia );
		ret.append( ", horaEntrada=" + horaEntrada );
		ret.append( ", horaSalida=" + horaSalida );
		ret.append( ", diaDescanso=" + diaDescanso );
		ret.append( ", comidaSalida=" + comidaSalida );
		ret.append( ", comidaEntrada=" + comidaEntrada );
		ret.append( ", periodoComida=" + periodoComida );
		ret.append( ", tolerancia=" + tolerancia );
		return ret.toString();
	}

}
