/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.tsp.gespro.dto;

import com.tsp.gespro.dao.*;
import com.tsp.gespro.factory.*;
import com.tsp.gespro.exceptions.*;
import java.io.Serializable;
import java.util.*;
import java.util.Date;

public class ConceptoRegistroFotografico implements Serializable
{
	/** 
	 * This attribute maps to the column ID_REGISTRO in the concepto_registro_fotografico table.
	 */
	protected int idRegistro;

	/** 
	 * This attribute represents whether the attribute idRegistro has been modified since being read from the database.
	 */
	protected boolean idRegistroModified = false;

	/** 
	 * This attribute maps to the column ID_EMPRESA in the concepto_registro_fotografico table.
	 */
	protected int idEmpresa;

	/** 
	 * This attribute represents whether the attribute idEmpresa has been modified since being read from the database.
	 */
	protected boolean idEmpresaModified = false;

	/** 
	 * This attribute maps to the column ID_CONCEPTO in the concepto_registro_fotografico table.
	 */
	protected int idConcepto;

	/** 
	 * This attribute represents whether the attribute idConcepto has been modified since being read from the database.
	 */
	protected boolean idConceptoModified = false;

	/** 
	 * This attribute maps to the column ID_CLIENTE in the concepto_registro_fotografico table.
	 */
	protected int idCliente;

	/** 
	 * This attribute represents whether the primitive attribute idCliente is null.
	 */
	protected boolean idClienteNull = true;

	/** 
	 * This attribute represents whether the attribute idCliente has been modified since being read from the database.
	 */
	protected boolean idClienteModified = false;

	/** 
	 * This attribute maps to the column ID_USUARIO in the concepto_registro_fotografico table.
	 */
	protected int idUsuario;

	/** 
	 * This attribute represents whether the primitive attribute idUsuario is null.
	 */
	protected boolean idUsuarioNull = true;

	/** 
	 * This attribute represents whether the attribute idUsuario has been modified since being read from the database.
	 */
	protected boolean idUsuarioModified = false;

	/** 
	 * This attribute maps to the column ID_TIPO_FOTO in the concepto_registro_fotografico table.
	 */
	protected int idTipoFoto;

	/** 
	 * This attribute represents whether the primitive attribute idTipoFoto is null.
	 */
	protected boolean idTipoFotoNull = true;

	/** 
	 * This attribute represents whether the attribute idTipoFoto has been modified since being read from the database.
	 */
	protected boolean idTipoFotoModified = false;

	/** 
	 * This attribute maps to the column ID_ESTATUS in the concepto_registro_fotografico table.
	 */
	protected int idEstatus;

	/** 
	 * This attribute represents whether the primitive attribute idEstatus is null.
	 */
	protected boolean idEstatusNull = true;

	/** 
	 * This attribute represents whether the attribute idEstatus has been modified since being read from the database.
	 */
	protected boolean idEstatusModified = false;

	/** 
	 * This attribute maps to the column NOMBRE_FOTO in the concepto_registro_fotografico table.
	 */
	protected String nombreFoto;

	/** 
	 * This attribute represents whether the attribute nombreFoto has been modified since being read from the database.
	 */
	protected boolean nombreFotoModified = false;

	/** 
	 * This attribute maps to the column COMENTARIO in the concepto_registro_fotografico table.
	 */
	protected String comentario;

	/** 
	 * This attribute represents whether the attribute comentario has been modified since being read from the database.
	 */
	protected boolean comentarioModified = false;

	/** 
	 * This attribute maps to the column FECHA_HORA in the concepto_registro_fotografico table.
	 */
	protected Date fechaHora;

	/** 
	 * This attribute represents whether the attribute fechaHora has been modified since being read from the database.
	 */
	protected boolean fechaHoraModified = false;

	/**
	 * Method 'ConceptoRegistroFotografico'
	 * 
	 */
	public ConceptoRegistroFotografico()
	{
	}

	/**
	 * Method 'getIdRegistro'
	 * 
	 * @return int
	 */
	public int getIdRegistro()
	{
		return idRegistro;
	}

	/**
	 * Method 'setIdRegistro'
	 * 
	 * @param idRegistro
	 */
	public void setIdRegistro(int idRegistro)
	{
		this.idRegistro = idRegistro;
		this.idRegistroModified = true;
	}

	/** 
	 * Sets the value of idRegistroModified
	 */
	public void setIdRegistroModified(boolean idRegistroModified)
	{
		this.idRegistroModified = idRegistroModified;
	}

	/** 
	 * Gets the value of idRegistroModified
	 */
	public boolean isIdRegistroModified()
	{
		return idRegistroModified;
	}

	/**
	 * Method 'getIdEmpresa'
	 * 
	 * @return int
	 */
	public int getIdEmpresa()
	{
		return idEmpresa;
	}

	/**
	 * Method 'setIdEmpresa'
	 * 
	 * @param idEmpresa
	 */
	public void setIdEmpresa(int idEmpresa)
	{
		this.idEmpresa = idEmpresa;
		this.idEmpresaModified = true;
	}

	/** 
	 * Sets the value of idEmpresaModified
	 */
	public void setIdEmpresaModified(boolean idEmpresaModified)
	{
		this.idEmpresaModified = idEmpresaModified;
	}

	/** 
	 * Gets the value of idEmpresaModified
	 */
	public boolean isIdEmpresaModified()
	{
		return idEmpresaModified;
	}

	/**
	 * Method 'getIdConcepto'
	 * 
	 * @return int
	 */
	public int getIdConcepto()
	{
		return idConcepto;
	}

	/**
	 * Method 'setIdConcepto'
	 * 
	 * @param idConcepto
	 */
	public void setIdConcepto(int idConcepto)
	{
		this.idConcepto = idConcepto;
		this.idConceptoModified = true;
	}

	/** 
	 * Sets the value of idConceptoModified
	 */
	public void setIdConceptoModified(boolean idConceptoModified)
	{
		this.idConceptoModified = idConceptoModified;
	}

	/** 
	 * Gets the value of idConceptoModified
	 */
	public boolean isIdConceptoModified()
	{
		return idConceptoModified;
	}

	/**
	 * Method 'getIdCliente'
	 * 
	 * @return int
	 */
	public int getIdCliente()
	{
		return idCliente;
	}

	/**
	 * Method 'setIdCliente'
	 * 
	 * @param idCliente
	 */
	public void setIdCliente(int idCliente)
	{
		this.idCliente = idCliente;
		this.idClienteNull = false;
		this.idClienteModified = true;
	}

	/**
	 * Method 'setIdClienteNull'
	 * 
	 * @param value
	 */
	public void setIdClienteNull(boolean value)
	{
		this.idClienteNull = value;
		this.idClienteModified = true;
	}

	/**
	 * Method 'isIdClienteNull'
	 * 
	 * @return boolean
	 */
	public boolean isIdClienteNull()
	{
		return idClienteNull;
	}

	/** 
	 * Sets the value of idClienteModified
	 */
	public void setIdClienteModified(boolean idClienteModified)
	{
		this.idClienteModified = idClienteModified;
	}

	/** 
	 * Gets the value of idClienteModified
	 */
	public boolean isIdClienteModified()
	{
		return idClienteModified;
	}

	/**
	 * Method 'getIdUsuario'
	 * 
	 * @return int
	 */
	public int getIdUsuario()
	{
		return idUsuario;
	}

	/**
	 * Method 'setIdUsuario'
	 * 
	 * @param idUsuario
	 */
	public void setIdUsuario(int idUsuario)
	{
		this.idUsuario = idUsuario;
		this.idUsuarioNull = false;
		this.idUsuarioModified = true;
	}

	/**
	 * Method 'setIdUsuarioNull'
	 * 
	 * @param value
	 */
	public void setIdUsuarioNull(boolean value)
	{
		this.idUsuarioNull = value;
		this.idUsuarioModified = true;
	}

	/**
	 * Method 'isIdUsuarioNull'
	 * 
	 * @return boolean
	 */
	public boolean isIdUsuarioNull()
	{
		return idUsuarioNull;
	}

	/** 
	 * Sets the value of idUsuarioModified
	 */
	public void setIdUsuarioModified(boolean idUsuarioModified)
	{
		this.idUsuarioModified = idUsuarioModified;
	}

	/** 
	 * Gets the value of idUsuarioModified
	 */
	public boolean isIdUsuarioModified()
	{
		return idUsuarioModified;
	}

	/**
	 * Method 'getIdTipoFoto'
	 * 
	 * @return int
	 */
	public int getIdTipoFoto()
	{
		return idTipoFoto;
	}

	/**
	 * Method 'setIdTipoFoto'
	 * 
	 * @param idTipoFoto
	 */
	public void setIdTipoFoto(int idTipoFoto)
	{
		this.idTipoFoto = idTipoFoto;
		this.idTipoFotoNull = false;
		this.idTipoFotoModified = true;
	}

	/**
	 * Method 'setIdTipoFotoNull'
	 * 
	 * @param value
	 */
	public void setIdTipoFotoNull(boolean value)
	{
		this.idTipoFotoNull = value;
		this.idTipoFotoModified = true;
	}

	/**
	 * Method 'isIdTipoFotoNull'
	 * 
	 * @return boolean
	 */
	public boolean isIdTipoFotoNull()
	{
		return idTipoFotoNull;
	}

	/** 
	 * Sets the value of idTipoFotoModified
	 */
	public void setIdTipoFotoModified(boolean idTipoFotoModified)
	{
		this.idTipoFotoModified = idTipoFotoModified;
	}

	/** 
	 * Gets the value of idTipoFotoModified
	 */
	public boolean isIdTipoFotoModified()
	{
		return idTipoFotoModified;
	}

	/**
	 * Method 'getIdEstatus'
	 * 
	 * @return int
	 */
	public int getIdEstatus()
	{
		return idEstatus;
	}

	/**
	 * Method 'setIdEstatus'
	 * 
	 * @param idEstatus
	 */
	public void setIdEstatus(int idEstatus)
	{
		this.idEstatus = idEstatus;
		this.idEstatusNull = false;
		this.idEstatusModified = true;
	}

	/**
	 * Method 'setIdEstatusNull'
	 * 
	 * @param value
	 */
	public void setIdEstatusNull(boolean value)
	{
		this.idEstatusNull = value;
		this.idEstatusModified = true;
	}

	/**
	 * Method 'isIdEstatusNull'
	 * 
	 * @return boolean
	 */
	public boolean isIdEstatusNull()
	{
		return idEstatusNull;
	}

	/** 
	 * Sets the value of idEstatusModified
	 */
	public void setIdEstatusModified(boolean idEstatusModified)
	{
		this.idEstatusModified = idEstatusModified;
	}

	/** 
	 * Gets the value of idEstatusModified
	 */
	public boolean isIdEstatusModified()
	{
		return idEstatusModified;
	}

	/**
	 * Method 'getNombreFoto'
	 * 
	 * @return String
	 */
	public String getNombreFoto()
	{
		return nombreFoto;
	}

	/**
	 * Method 'setNombreFoto'
	 * 
	 * @param nombreFoto
	 */
	public void setNombreFoto(String nombreFoto)
	{
		this.nombreFoto = nombreFoto;
		this.nombreFotoModified = true;
	}

	/** 
	 * Sets the value of nombreFotoModified
	 */
	public void setNombreFotoModified(boolean nombreFotoModified)
	{
		this.nombreFotoModified = nombreFotoModified;
	}

	/** 
	 * Gets the value of nombreFotoModified
	 */
	public boolean isNombreFotoModified()
	{
		return nombreFotoModified;
	}

	/**
	 * Method 'getComentario'
	 * 
	 * @return String
	 */
	public String getComentario()
	{
		return comentario;
	}

	/**
	 * Method 'setComentario'
	 * 
	 * @param comentario
	 */
	public void setComentario(String comentario)
	{
		this.comentario = comentario;
		this.comentarioModified = true;
	}

	/** 
	 * Sets the value of comentarioModified
	 */
	public void setComentarioModified(boolean comentarioModified)
	{
		this.comentarioModified = comentarioModified;
	}

	/** 
	 * Gets the value of comentarioModified
	 */
	public boolean isComentarioModified()
	{
		return comentarioModified;
	}

	/**
	 * Method 'getFechaHora'
	 * 
	 * @return Date
	 */
	public Date getFechaHora()
	{
		return fechaHora;
	}

	/**
	 * Method 'setFechaHora'
	 * 
	 * @param fechaHora
	 */
	public void setFechaHora(Date fechaHora)
	{
		this.fechaHora = fechaHora;
		this.fechaHoraModified = true;
	}

	/** 
	 * Sets the value of fechaHoraModified
	 */
	public void setFechaHoraModified(boolean fechaHoraModified)
	{
		this.fechaHoraModified = fechaHoraModified;
	}

	/** 
	 * Gets the value of fechaHoraModified
	 */
	public boolean isFechaHoraModified()
	{
		return fechaHoraModified;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof ConceptoRegistroFotografico)) {
			return false;
		}
		
		final ConceptoRegistroFotografico _cast = (ConceptoRegistroFotografico) _other;
		if (idRegistro != _cast.idRegistro) {
			return false;
		}
		
		if (idRegistroModified != _cast.idRegistroModified) {
			return false;
		}
		
		if (idEmpresa != _cast.idEmpresa) {
			return false;
		}
		
		if (idEmpresaModified != _cast.idEmpresaModified) {
			return false;
		}
		
		if (idConcepto != _cast.idConcepto) {
			return false;
		}
		
		if (idConceptoModified != _cast.idConceptoModified) {
			return false;
		}
		
		if (idCliente != _cast.idCliente) {
			return false;
		}
		
		if (idClienteNull != _cast.idClienteNull) {
			return false;
		}
		
		if (idClienteModified != _cast.idClienteModified) {
			return false;
		}
		
		if (idUsuario != _cast.idUsuario) {
			return false;
		}
		
		if (idUsuarioNull != _cast.idUsuarioNull) {
			return false;
		}
		
		if (idUsuarioModified != _cast.idUsuarioModified) {
			return false;
		}
		
		if (idTipoFoto != _cast.idTipoFoto) {
			return false;
		}
		
		if (idTipoFotoNull != _cast.idTipoFotoNull) {
			return false;
		}
		
		if (idTipoFotoModified != _cast.idTipoFotoModified) {
			return false;
		}
		
		if (idEstatus != _cast.idEstatus) {
			return false;
		}
		
		if (idEstatusNull != _cast.idEstatusNull) {
			return false;
		}
		
		if (idEstatusModified != _cast.idEstatusModified) {
			return false;
		}
		
		if (nombreFoto == null ? _cast.nombreFoto != nombreFoto : !nombreFoto.equals( _cast.nombreFoto )) {
			return false;
		}
		
		if (nombreFotoModified != _cast.nombreFotoModified) {
			return false;
		}
		
		if (comentario == null ? _cast.comentario != comentario : !comentario.equals( _cast.comentario )) {
			return false;
		}
		
		if (comentarioModified != _cast.comentarioModified) {
			return false;
		}
		
		if (fechaHora == null ? _cast.fechaHora != fechaHora : !fechaHora.equals( _cast.fechaHora )) {
			return false;
		}
		
		if (fechaHoraModified != _cast.fechaHoraModified) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		_hashCode = 29 * _hashCode + idRegistro;
		_hashCode = 29 * _hashCode + (idRegistroModified ? 1 : 0);
		_hashCode = 29 * _hashCode + idEmpresa;
		_hashCode = 29 * _hashCode + (idEmpresaModified ? 1 : 0);
		_hashCode = 29 * _hashCode + idConcepto;
		_hashCode = 29 * _hashCode + (idConceptoModified ? 1 : 0);
		_hashCode = 29 * _hashCode + idCliente;
		_hashCode = 29 * _hashCode + (idClienteNull ? 1 : 0);
		_hashCode = 29 * _hashCode + (idClienteModified ? 1 : 0);
		_hashCode = 29 * _hashCode + idUsuario;
		_hashCode = 29 * _hashCode + (idUsuarioNull ? 1 : 0);
		_hashCode = 29 * _hashCode + (idUsuarioModified ? 1 : 0);
		_hashCode = 29 * _hashCode + idTipoFoto;
		_hashCode = 29 * _hashCode + (idTipoFotoNull ? 1 : 0);
		_hashCode = 29 * _hashCode + (idTipoFotoModified ? 1 : 0);
		_hashCode = 29 * _hashCode + idEstatus;
		_hashCode = 29 * _hashCode + (idEstatusNull ? 1 : 0);
		_hashCode = 29 * _hashCode + (idEstatusModified ? 1 : 0);
		if (nombreFoto != null) {
			_hashCode = 29 * _hashCode + nombreFoto.hashCode();
		}
		
		_hashCode = 29 * _hashCode + (nombreFotoModified ? 1 : 0);
		if (comentario != null) {
			_hashCode = 29 * _hashCode + comentario.hashCode();
		}
		
		_hashCode = 29 * _hashCode + (comentarioModified ? 1 : 0);
		if (fechaHora != null) {
			_hashCode = 29 * _hashCode + fechaHora.hashCode();
		}
		
		_hashCode = 29 * _hashCode + (fechaHoraModified ? 1 : 0);
		return _hashCode;
	}

	/**
	 * Method 'createPk'
	 * 
	 * @return ConceptoRegistroFotograficoPk
	 */
	public ConceptoRegistroFotograficoPk createPk()
	{
		return new ConceptoRegistroFotograficoPk(idRegistro);
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "com.tsp.gespro.dto.ConceptoRegistroFotografico: " );
		ret.append( "idRegistro=" + idRegistro );
		ret.append( ", idEmpresa=" + idEmpresa );
		ret.append( ", idConcepto=" + idConcepto );
		ret.append( ", idCliente=" + idCliente );
		ret.append( ", idUsuario=" + idUsuario );
		ret.append( ", idTipoFoto=" + idTipoFoto );
		ret.append( ", idEstatus=" + idEstatus );
		ret.append( ", nombreFoto=" + nombreFoto );
		ret.append( ", comentario=" + comentario );
		ret.append( ", fechaHora=" + fechaHora );
		return ret.toString();
	}

}
