/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.tsp.gespro.dto;

import com.tsp.gespro.dao.*;
import com.tsp.gespro.factory.*;
import com.tsp.gespro.exceptions.*;
import java.io.Serializable;
import java.util.*;
import java.util.Date;

public class MovilMensaje implements Serializable
{
	/** 
	 * This attribute maps to the column ID_MOVIL_MENSAJE in the movil_mensaje table.
	 */
	protected int idMovilMensaje;

	/** 
	 * This attribute represents whether the attribute idMovilMensaje has been modified since being read from the database.
	 */
	protected boolean idMovilMensajeModified = false;

	/** 
	 * This attribute maps to the column EMISOR_TIPO in the movil_mensaje table.
	 */
	protected int emisorTipo;

	/** 
	 * This attribute represents whether the attribute emisorTipo has been modified since being read from the database.
	 */
	protected boolean emisorTipoModified = false;

	/** 
	 * This attribute maps to the column ID_USUARIO_EMISOR in the movil_mensaje table.
	 */
	protected int idUsuarioEmisor;

	/** 
	 * This attribute represents whether the primitive attribute idUsuarioEmisor is null.
	 */
	protected boolean idUsuarioEmisorNull = true;

	/** 
	 * This attribute represents whether the attribute idUsuarioEmisor has been modified since being read from the database.
	 */
	protected boolean idUsuarioEmisorModified = false;

	/** 
	 * This attribute maps to the column RECEPTOR_TIPO in the movil_mensaje table.
	 */
	protected int receptorTipo;

	/** 
	 * This attribute represents whether the attribute receptorTipo has been modified since being read from the database.
	 */
	protected boolean receptorTipoModified = false;

	/** 
	 * This attribute maps to the column ID_USUARIO_RECEPTOR in the movil_mensaje table.
	 */
	protected int idUsuarioReceptor;

	/** 
	 * This attribute represents whether the primitive attribute idUsuarioReceptor is null.
	 */
	protected boolean idUsuarioReceptorNull = true;

	/** 
	 * This attribute represents whether the attribute idUsuarioReceptor has been modified since being read from the database.
	 */
	protected boolean idUsuarioReceptorModified = false;

	/** 
	 * This attribute maps to the column FECHA_EMISION in the movil_mensaje table.
	 */
	protected Date fechaEmision;

	/** 
	 * This attribute represents whether the attribute fechaEmision has been modified since being read from the database.
	 */
	protected boolean fechaEmisionModified = false;

	/** 
	 * This attribute maps to the column FECHA_RECEPCION in the movil_mensaje table.
	 */
	protected Date fechaRecepcion;

	/** 
	 * This attribute represents whether the attribute fechaRecepcion has been modified since being read from the database.
	 */
	protected boolean fechaRecepcionModified = false;

	/** 
	 * This attribute maps to the column MENSAJE in the movil_mensaje table.
	 */
	protected String mensaje;

	/** 
	 * This attribute represents whether the attribute mensaje has been modified since being read from the database.
	 */
	protected boolean mensajeModified = false;

	/** 
	 * This attribute maps to the column RECIBIDO in the movil_mensaje table.
	 */
	protected int recibido;

	/** 
	 * This attribute represents whether the attribute recibido has been modified since being read from the database.
	 */
	protected boolean recibidoModified = false;

	/**
	 * Method 'MovilMensaje'
	 * 
	 */
	public MovilMensaje()
	{
	}

	/**
	 * Method 'getIdMovilMensaje'
	 * 
	 * @return int
	 */
	public int getIdMovilMensaje()
	{
		return idMovilMensaje;
	}

	/**
	 * Method 'setIdMovilMensaje'
	 * 
	 * @param idMovilMensaje
	 */
	public void setIdMovilMensaje(int idMovilMensaje)
	{
		this.idMovilMensaje = idMovilMensaje;
		this.idMovilMensajeModified = true;
	}

	/** 
	 * Sets the value of idMovilMensajeModified
	 */
	public void setIdMovilMensajeModified(boolean idMovilMensajeModified)
	{
		this.idMovilMensajeModified = idMovilMensajeModified;
	}

	/** 
	 * Gets the value of idMovilMensajeModified
	 */
	public boolean isIdMovilMensajeModified()
	{
		return idMovilMensajeModified;
	}

	/**
	 * Method 'getEmisorTipo'
	 * 
	 * @return int
	 */
	public int getEmisorTipo()
	{
		return emisorTipo;
	}

	/**
	 * Method 'setEmisorTipo'
	 * 
	 * @param emisorTipo
	 */
	public void setEmisorTipo(int emisorTipo)
	{
		this.emisorTipo = emisorTipo;
		this.emisorTipoModified = true;
	}

	/** 
	 * Sets the value of emisorTipoModified
	 */
	public void setEmisorTipoModified(boolean emisorTipoModified)
	{
		this.emisorTipoModified = emisorTipoModified;
	}

	/** 
	 * Gets the value of emisorTipoModified
	 */
	public boolean isEmisorTipoModified()
	{
		return emisorTipoModified;
	}

	/**
	 * Method 'getIdUsuarioEmisor'
	 * 
	 * @return int
	 */
	public int getIdUsuarioEmisor()
	{
		return idUsuarioEmisor;
	}

	/**
	 * Method 'setIdUsuarioEmisor'
	 * 
	 * @param idUsuarioEmisor
	 */
	public void setIdUsuarioEmisor(int idUsuarioEmisor)
	{
		this.idUsuarioEmisor = idUsuarioEmisor;
		this.idUsuarioEmisorNull = false;
		this.idUsuarioEmisorModified = true;
	}

	/**
	 * Method 'setIdUsuarioEmisorNull'
	 * 
	 * @param value
	 */
	public void setIdUsuarioEmisorNull(boolean value)
	{
		this.idUsuarioEmisorNull = value;
		this.idUsuarioEmisorModified = true;
	}

	/**
	 * Method 'isIdUsuarioEmisorNull'
	 * 
	 * @return boolean
	 */
	public boolean isIdUsuarioEmisorNull()
	{
		return idUsuarioEmisorNull;
	}

	/** 
	 * Sets the value of idUsuarioEmisorModified
	 */
	public void setIdUsuarioEmisorModified(boolean idUsuarioEmisorModified)
	{
		this.idUsuarioEmisorModified = idUsuarioEmisorModified;
	}

	/** 
	 * Gets the value of idUsuarioEmisorModified
	 */
	public boolean isIdUsuarioEmisorModified()
	{
		return idUsuarioEmisorModified;
	}

	/**
	 * Method 'getReceptorTipo'
	 * 
	 * @return int
	 */
	public int getReceptorTipo()
	{
		return receptorTipo;
	}

	/**
	 * Method 'setReceptorTipo'
	 * 
	 * @param receptorTipo
	 */
	public void setReceptorTipo(int receptorTipo)
	{
		this.receptorTipo = receptorTipo;
		this.receptorTipoModified = true;
	}

	/** 
	 * Sets the value of receptorTipoModified
	 */
	public void setReceptorTipoModified(boolean receptorTipoModified)
	{
		this.receptorTipoModified = receptorTipoModified;
	}

	/** 
	 * Gets the value of receptorTipoModified
	 */
	public boolean isReceptorTipoModified()
	{
		return receptorTipoModified;
	}

	/**
	 * Method 'getIdUsuarioReceptor'
	 * 
	 * @return int
	 */
	public int getIdUsuarioReceptor()
	{
		return idUsuarioReceptor;
	}

	/**
	 * Method 'setIdUsuarioReceptor'
	 * 
	 * @param idUsuarioReceptor
	 */
	public void setIdUsuarioReceptor(int idUsuarioReceptor)
	{
		this.idUsuarioReceptor = idUsuarioReceptor;
		this.idUsuarioReceptorNull = false;
		this.idUsuarioReceptorModified = true;
	}

	/**
	 * Method 'setIdUsuarioReceptorNull'
	 * 
	 * @param value
	 */
	public void setIdUsuarioReceptorNull(boolean value)
	{
		this.idUsuarioReceptorNull = value;
		this.idUsuarioReceptorModified = true;
	}

	/**
	 * Method 'isIdUsuarioReceptorNull'
	 * 
	 * @return boolean
	 */
	public boolean isIdUsuarioReceptorNull()
	{
		return idUsuarioReceptorNull;
	}

	/** 
	 * Sets the value of idUsuarioReceptorModified
	 */
	public void setIdUsuarioReceptorModified(boolean idUsuarioReceptorModified)
	{
		this.idUsuarioReceptorModified = idUsuarioReceptorModified;
	}

	/** 
	 * Gets the value of idUsuarioReceptorModified
	 */
	public boolean isIdUsuarioReceptorModified()
	{
		return idUsuarioReceptorModified;
	}

	/**
	 * Method 'getFechaEmision'
	 * 
	 * @return Date
	 */
	public Date getFechaEmision()
	{
		return fechaEmision;
	}

	/**
	 * Method 'setFechaEmision'
	 * 
	 * @param fechaEmision
	 */
	public void setFechaEmision(Date fechaEmision)
	{
		this.fechaEmision = fechaEmision;
		this.fechaEmisionModified = true;
	}

	/** 
	 * Sets the value of fechaEmisionModified
	 */
	public void setFechaEmisionModified(boolean fechaEmisionModified)
	{
		this.fechaEmisionModified = fechaEmisionModified;
	}

	/** 
	 * Gets the value of fechaEmisionModified
	 */
	public boolean isFechaEmisionModified()
	{
		return fechaEmisionModified;
	}

	/**
	 * Method 'getFechaRecepcion'
	 * 
	 * @return Date
	 */
	public Date getFechaRecepcion()
	{
		return fechaRecepcion;
	}

	/**
	 * Method 'setFechaRecepcion'
	 * 
	 * @param fechaRecepcion
	 */
	public void setFechaRecepcion(Date fechaRecepcion)
	{
		this.fechaRecepcion = fechaRecepcion;
		this.fechaRecepcionModified = true;
	}

	/** 
	 * Sets the value of fechaRecepcionModified
	 */
	public void setFechaRecepcionModified(boolean fechaRecepcionModified)
	{
		this.fechaRecepcionModified = fechaRecepcionModified;
	}

	/** 
	 * Gets the value of fechaRecepcionModified
	 */
	public boolean isFechaRecepcionModified()
	{
		return fechaRecepcionModified;
	}

	/**
	 * Method 'getMensaje'
	 * 
	 * @return String
	 */
	public String getMensaje()
	{
		return mensaje;
	}

	/**
	 * Method 'setMensaje'
	 * 
	 * @param mensaje
	 */
	public void setMensaje(String mensaje)
	{
		this.mensaje = mensaje;
		this.mensajeModified = true;
	}

	/** 
	 * Sets the value of mensajeModified
	 */
	public void setMensajeModified(boolean mensajeModified)
	{
		this.mensajeModified = mensajeModified;
	}

	/** 
	 * Gets the value of mensajeModified
	 */
	public boolean isMensajeModified()
	{
		return mensajeModified;
	}

	/**
	 * Method 'getRecibido'
	 * 
	 * @return int
	 */
	public int getRecibido()
	{
		return recibido;
	}

	/**
	 * Method 'setRecibido'
	 * 
	 * @param recibido
	 */
	public void setRecibido(int recibido)
	{
		this.recibido = recibido;
		this.recibidoModified = true;
	}

	/** 
	 * Sets the value of recibidoModified
	 */
	public void setRecibidoModified(boolean recibidoModified)
	{
		this.recibidoModified = recibidoModified;
	}

	/** 
	 * Gets the value of recibidoModified
	 */
	public boolean isRecibidoModified()
	{
		return recibidoModified;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof MovilMensaje)) {
			return false;
		}
		
		final MovilMensaje _cast = (MovilMensaje) _other;
		if (idMovilMensaje != _cast.idMovilMensaje) {
			return false;
		}
		
		if (idMovilMensajeModified != _cast.idMovilMensajeModified) {
			return false;
		}
		
		if (emisorTipo != _cast.emisorTipo) {
			return false;
		}
		
		if (emisorTipoModified != _cast.emisorTipoModified) {
			return false;
		}
		
		if (idUsuarioEmisor != _cast.idUsuarioEmisor) {
			return false;
		}
		
		if (idUsuarioEmisorNull != _cast.idUsuarioEmisorNull) {
			return false;
		}
		
		if (idUsuarioEmisorModified != _cast.idUsuarioEmisorModified) {
			return false;
		}
		
		if (receptorTipo != _cast.receptorTipo) {
			return false;
		}
		
		if (receptorTipoModified != _cast.receptorTipoModified) {
			return false;
		}
		
		if (idUsuarioReceptor != _cast.idUsuarioReceptor) {
			return false;
		}
		
		if (idUsuarioReceptorNull != _cast.idUsuarioReceptorNull) {
			return false;
		}
		
		if (idUsuarioReceptorModified != _cast.idUsuarioReceptorModified) {
			return false;
		}
		
		if (fechaEmision == null ? _cast.fechaEmision != fechaEmision : !fechaEmision.equals( _cast.fechaEmision )) {
			return false;
		}
		
		if (fechaEmisionModified != _cast.fechaEmisionModified) {
			return false;
		}
		
		if (fechaRecepcion == null ? _cast.fechaRecepcion != fechaRecepcion : !fechaRecepcion.equals( _cast.fechaRecepcion )) {
			return false;
		}
		
		if (fechaRecepcionModified != _cast.fechaRecepcionModified) {
			return false;
		}
		
		if (mensaje == null ? _cast.mensaje != mensaje : !mensaje.equals( _cast.mensaje )) {
			return false;
		}
		
		if (mensajeModified != _cast.mensajeModified) {
			return false;
		}
		
		if (recibido != _cast.recibido) {
			return false;
		}
		
		if (recibidoModified != _cast.recibidoModified) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		_hashCode = 29 * _hashCode + idMovilMensaje;
		_hashCode = 29 * _hashCode + (idMovilMensajeModified ? 1 : 0);
		_hashCode = 29 * _hashCode + emisorTipo;
		_hashCode = 29 * _hashCode + (emisorTipoModified ? 1 : 0);
		_hashCode = 29 * _hashCode + idUsuarioEmisor;
		_hashCode = 29 * _hashCode + (idUsuarioEmisorNull ? 1 : 0);
		_hashCode = 29 * _hashCode + (idUsuarioEmisorModified ? 1 : 0);
		_hashCode = 29 * _hashCode + receptorTipo;
		_hashCode = 29 * _hashCode + (receptorTipoModified ? 1 : 0);
		_hashCode = 29 * _hashCode + idUsuarioReceptor;
		_hashCode = 29 * _hashCode + (idUsuarioReceptorNull ? 1 : 0);
		_hashCode = 29 * _hashCode + (idUsuarioReceptorModified ? 1 : 0);
		if (fechaEmision != null) {
			_hashCode = 29 * _hashCode + fechaEmision.hashCode();
		}
		
		_hashCode = 29 * _hashCode + (fechaEmisionModified ? 1 : 0);
		if (fechaRecepcion != null) {
			_hashCode = 29 * _hashCode + fechaRecepcion.hashCode();
		}
		
		_hashCode = 29 * _hashCode + (fechaRecepcionModified ? 1 : 0);
		if (mensaje != null) {
			_hashCode = 29 * _hashCode + mensaje.hashCode();
		}
		
		_hashCode = 29 * _hashCode + (mensajeModified ? 1 : 0);
		_hashCode = 29 * _hashCode + recibido;
		_hashCode = 29 * _hashCode + (recibidoModified ? 1 : 0);
		return _hashCode;
	}

	/**
	 * Method 'createPk'
	 * 
	 * @return MovilMensajePk
	 */
	public MovilMensajePk createPk()
	{
		return new MovilMensajePk(idMovilMensaje);
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "com.tsp.gespro.dto.MovilMensaje: " );
		ret.append( "idMovilMensaje=" + idMovilMensaje );
		ret.append( ", emisorTipo=" + emisorTipo );
		ret.append( ", idUsuarioEmisor=" + idUsuarioEmisor );
		ret.append( ", receptorTipo=" + receptorTipo );
		ret.append( ", idUsuarioReceptor=" + idUsuarioReceptor );
		ret.append( ", fechaEmision=" + fechaEmision );
		ret.append( ", fechaRecepcion=" + fechaRecepcion );
		ret.append( ", mensaje=" + mensaje );
		ret.append( ", recibido=" + recibido );
		return ret.toString();
	}

}
