/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.tsp.gespro.jdbc;

import com.tsp.gespro.dao.*;
import com.tsp.gespro.factory.*;
import com.tsp.gespro.dto.*;
import com.tsp.gespro.exceptions.*;
import java.sql.Connection;
import java.util.Collection;
import java.sql.PreparedStatement;
import java.sql.Statement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Time;
import java.util.List;
import java.util.Iterator;
import java.util.ArrayList;

public class HorarioUsuarioDaoImpl extends AbstractDAO implements HorarioUsuarioDao
{
	/** 
	 * The factory class for this DAO has two versions of the create() method - one that
takes no arguments and one that takes a Connection argument. If the Connection version
is chosen then the connection will be stored in this attribute and will be used by all
calls to this DAO, otherwise a new Connection will be allocated for each operation.
	 */
	protected java.sql.Connection userConn;

	/** 
	 * All finder methods in this class use this SELECT constant to build their queries
	 */
	protected final String SQL_SELECT = "SELECT ID_HORARIO, NOMBRE_HORARIO, ID_EMPRESA, ID_ESTATUS FROM " + getTableName() + "";

	/** 
	 * Finder methods will pass this value to the JDBC setMaxRows method
	 */
	protected int maxRows;

	/** 
	 * SQL INSERT statement for this table
	 */
	protected final String SQL_INSERT = "INSERT INTO " + getTableName() + " ( ID_HORARIO, NOMBRE_HORARIO, ID_EMPRESA, ID_ESTATUS ) VALUES ( ?, ?, ?, ? )";

	/** 
	 * SQL UPDATE statement for this table
	 */
	protected final String SQL_UPDATE = "UPDATE " + getTableName() + " SET ID_HORARIO = ?, NOMBRE_HORARIO = ?, ID_EMPRESA = ?, ID_ESTATUS = ? WHERE ID_HORARIO = ?";

	/** 
	 * SQL DELETE statement for this table
	 */
	protected final String SQL_DELETE = "DELETE FROM " + getTableName() + " WHERE ID_HORARIO = ?";

	/** 
	 * Index of column ID_HORARIO
	 */
	protected static final int COLUMN_ID_HORARIO = 1;

	/** 
	 * Index of column NOMBRE_HORARIO
	 */
	protected static final int COLUMN_NOMBRE_HORARIO = 2;

	/** 
	 * Index of column ID_EMPRESA
	 */
	protected static final int COLUMN_ID_EMPRESA = 3;

	/** 
	 * Index of column ID_ESTATUS
	 */
	protected static final int COLUMN_ID_ESTATUS = 4;

	/** 
	 * Number of columns
	 */
	protected static final int NUMBER_OF_COLUMNS = 4;

	/** 
	 * Index of primary-key column ID_HORARIO
	 */
	protected static final int PK_COLUMN_ID_HORARIO = 1;

	/** 
	 * Inserts a new row in the horario_usuario table.
	 */
	public HorarioUsuarioPk insert(HorarioUsuario dto) throws HorarioUsuarioDaoException
	{
		long t1 = System.currentTimeMillis();
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		ResultSet rs = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			StringBuffer sql = new StringBuffer();
			StringBuffer values = new StringBuffer();
			sql.append( "INSERT INTO " + getTableName() + " (" );
			int modifiedCount = 0;
			if (dto.isIdHorarioModified()) {
				if (modifiedCount>0) {
					sql.append( ", " );
					values.append( ", " );
				}
		
				sql.append( "ID_HORARIO" );
				values.append( "?" );
				modifiedCount++;
			}
		
			if (dto.isNombreHorarioModified()) {
				if (modifiedCount>0) {
					sql.append( ", " );
					values.append( ", " );
				}
		
				sql.append( "NOMBRE_HORARIO" );
				values.append( "?" );
				modifiedCount++;
			}
		
			if (dto.isIdEmpresaModified()) {
				if (modifiedCount>0) {
					sql.append( ", " );
					values.append( ", " );
				}
		
				sql.append( "ID_EMPRESA" );
				values.append( "?" );
				modifiedCount++;
			}
		
			if (dto.isIdEstatusModified()) {
				if (modifiedCount>0) {
					sql.append( ", " );
					values.append( ", " );
				}
		
				sql.append( "ID_ESTATUS" );
				values.append( "?" );
				modifiedCount++;
			}
		
			if (modifiedCount==0) {
				// nothing to insert
				throw new IllegalStateException( "Nothing to insert" );
			}
		
			sql.append( ") VALUES (" );
			sql.append( values );
			sql.append( ")" );
			stmt = conn.prepareStatement( sql.toString(), Statement.RETURN_GENERATED_KEYS );
			int index = 1;
			if (dto.isIdHorarioModified()) {
				stmt.setInt( index++, dto.getIdHorario() );
			}
		
			if (dto.isNombreHorarioModified()) {
				stmt.setString( index++, dto.getNombreHorario() );
			}
		
			if (dto.isIdEmpresaModified()) {
				stmt.setInt( index++, dto.getIdEmpresa() );
			}
		
			if (dto.isIdEstatusModified()) {
				if (dto.isIdEstatusNull()) {
					stmt.setNull( index++, java.sql.Types.INTEGER );
				} else {
					stmt.setInt( index++, dto.getIdEstatus() );
				}
		
			}
		
			System.out.println( "Executing " + sql.toString() + " with values: " + dto );
			int rows = stmt.executeUpdate();
			long t2 = System.currentTimeMillis();
			System.out.println( rows + " rows affected (" + (t2-t1) + " ms)" );
		
			// retrieve values from auto-increment columns
			rs = stmt.getGeneratedKeys();
			if (rs != null && rs.next()) {
				dto.setIdHorario( rs.getInt( 1 ) );
			}
		
			reset(dto);
			return dto.createPk();
		}
		catch (Exception _e) {
			_e.printStackTrace();
			throw new HorarioUsuarioDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

	/** 
	 * Updates a single row in the horario_usuario table.
	 */
	public void update(HorarioUsuarioPk pk, HorarioUsuario dto) throws HorarioUsuarioDaoException
	{
		long t1 = System.currentTimeMillis();
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			StringBuffer sql = new StringBuffer();
			sql.append( "UPDATE " + getTableName() + " SET " );
			boolean modified = false;
			if (dto.isIdHorarioModified()) {
				if (modified) {
					sql.append( ", " );
				}
		
				sql.append( "ID_HORARIO=?" );
				modified=true;
			}
		
			if (dto.isNombreHorarioModified()) {
				if (modified) {
					sql.append( ", " );
				}
		
				sql.append( "NOMBRE_HORARIO=?" );
				modified=true;
			}
		
			if (dto.isIdEmpresaModified()) {
				if (modified) {
					sql.append( ", " );
				}
		
				sql.append( "ID_EMPRESA=?" );
				modified=true;
			}
		
			if (dto.isIdEstatusModified()) {
				if (modified) {
					sql.append( ", " );
				}
		
				sql.append( "ID_ESTATUS=?" );
				modified=true;
			}
		
			if (!modified) {
				// nothing to update
				return;
			}
		
			sql.append( " WHERE ID_HORARIO=?" );
			System.out.println( "Executing " + sql.toString() + " with values: " + dto );
			stmt = conn.prepareStatement( sql.toString() );
			int index = 1;
			if (dto.isIdHorarioModified()) {
				stmt.setInt( index++, dto.getIdHorario() );
			}
		
			if (dto.isNombreHorarioModified()) {
				stmt.setString( index++, dto.getNombreHorario() );
			}
		
			if (dto.isIdEmpresaModified()) {
				stmt.setInt( index++, dto.getIdEmpresa() );
			}
		
			if (dto.isIdEstatusModified()) {
				if (dto.isIdEstatusNull()) {
					stmt.setNull( index++, java.sql.Types.INTEGER );
				} else {
					stmt.setInt( index++, dto.getIdEstatus() );
				}
		
			}
		
			stmt.setInt( index++, pk.getIdHorario() );
			int rows = stmt.executeUpdate();
			reset(dto);
			long t2 = System.currentTimeMillis();
			System.out.println( rows + " rows affected (" + (t2-t1) + " ms)" );
		}
		catch (Exception _e) {
			_e.printStackTrace();
			throw new HorarioUsuarioDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

	/** 
	 * Deletes a single row in the horario_usuario table.
	 */
	public void delete(HorarioUsuarioPk pk) throws HorarioUsuarioDaoException
	{
		long t1 = System.currentTimeMillis();
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			System.out.println( "Executing " + SQL_DELETE + " with PK: " + pk );
			stmt = conn.prepareStatement( SQL_DELETE );
			stmt.setInt( 1, pk.getIdHorario() );
			int rows = stmt.executeUpdate();
			long t2 = System.currentTimeMillis();
			System.out.println( rows + " rows affected (" + (t2-t1) + " ms)" );
		}
		catch (Exception _e) {
			_e.printStackTrace();
			throw new HorarioUsuarioDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

	/** 
	 * Returns the rows from the horario_usuario table that matches the specified primary-key value.
	 */
	public HorarioUsuario findByPrimaryKey(HorarioUsuarioPk pk) throws HorarioUsuarioDaoException
	{
		return findByPrimaryKey( pk.getIdHorario() );
	}

	/** 
	 * Returns all rows from the horario_usuario table that match the criteria 'ID_HORARIO = :idHorario'.
	 */
	public HorarioUsuario findByPrimaryKey(int idHorario) throws HorarioUsuarioDaoException
	{
		HorarioUsuario ret[] = findByDynamicSelect( SQL_SELECT + " WHERE ID_HORARIO = ?", new Object[] {  new Integer(idHorario) } );
		return ret.length==0 ? null : ret[0];
	}

	/** 
	 * Returns all rows from the horario_usuario table that match the criteria ''.
	 */
	public HorarioUsuario[] findAll() throws HorarioUsuarioDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " ORDER BY ID_HORARIO", null );
	}

	/** 
	 * Returns all rows from the horario_usuario table that match the criteria 'ID_HORARIO = :idHorario'.
	 */
	public HorarioUsuario[] findWhereIdHorarioEquals(int idHorario) throws HorarioUsuarioDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE ID_HORARIO = ? ORDER BY ID_HORARIO", new Object[] {  new Integer(idHorario) } );
	}

	/** 
	 * Returns all rows from the horario_usuario table that match the criteria 'NOMBRE_HORARIO = :nombreHorario'.
	 */
	public HorarioUsuario[] findWhereNombreHorarioEquals(String nombreHorario) throws HorarioUsuarioDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE NOMBRE_HORARIO = ? ORDER BY NOMBRE_HORARIO", new Object[] { nombreHorario } );
	}

	/** 
	 * Returns all rows from the horario_usuario table that match the criteria 'ID_EMPRESA = :idEmpresa'.
	 */
	public HorarioUsuario[] findWhereIdEmpresaEquals(int idEmpresa) throws HorarioUsuarioDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE ID_EMPRESA = ? ORDER BY ID_EMPRESA", new Object[] {  new Integer(idEmpresa) } );
	}

	/** 
	 * Returns all rows from the horario_usuario table that match the criteria 'ID_ESTATUS = :idEstatus'.
	 */
	public HorarioUsuario[] findWhereIdEstatusEquals(int idEstatus) throws HorarioUsuarioDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE ID_ESTATUS = ? ORDER BY ID_ESTATUS", new Object[] {  new Integer(idEstatus) } );
	}

	/**
	 * Method 'HorarioUsuarioDaoImpl'
	 * 
	 */
	public HorarioUsuarioDaoImpl()
	{
	}

	/**
	 * Method 'HorarioUsuarioDaoImpl'
	 * 
	 * @param userConn
	 */
	public HorarioUsuarioDaoImpl(final java.sql.Connection userConn)
	{
		this.userConn = userConn;
	}

	/** 
	 * Sets the value of maxRows
	 */
	public void setMaxRows(int maxRows)
	{
		this.maxRows = maxRows;
	}

	/** 
	 * Gets the value of maxRows
	 */
	public int getMaxRows()
	{
		return maxRows;
	}

	/**
	 * Method 'getTableName'
	 * 
	 * @return String
	 */
	public String getTableName()
	{
		return "horario_usuario";
	}

	/** 
	 * Fetches a single row from the result set
	 */
	protected HorarioUsuario fetchSingleResult(ResultSet rs) throws SQLException
	{
		if (rs.next()) {
			HorarioUsuario dto = new HorarioUsuario();
			populateDto( dto, rs);
			return dto;
		} else {
			return null;
		}
		
	}

	/** 
	 * Fetches multiple rows from the result set
	 */
	protected HorarioUsuario[] fetchMultiResults(ResultSet rs) throws SQLException
	{
		Collection resultList = new ArrayList();
		while (rs.next()) {
			HorarioUsuario dto = new HorarioUsuario();
			populateDto( dto, rs);
			resultList.add( dto );
		}
		
		HorarioUsuario ret[] = new HorarioUsuario[ resultList.size() ];
		resultList.toArray( ret );
		return ret;
	}

	/** 
	 * Populates a DTO with data from a ResultSet
	 */
	protected void populateDto(HorarioUsuario dto, ResultSet rs) throws SQLException
	{
		dto.setIdHorario( rs.getInt( COLUMN_ID_HORARIO ) );
		dto.setNombreHorario( rs.getString( COLUMN_NOMBRE_HORARIO ) );
		dto.setIdEmpresa( rs.getInt( COLUMN_ID_EMPRESA ) );
		dto.setIdEstatus( rs.getInt( COLUMN_ID_ESTATUS ) );
		if (rs.wasNull()) {
			dto.setIdEstatusNull( true );
		}
		
		reset(dto);
	}

	/** 
	 * Resets the modified attributes in the DTO
	 */
	protected void reset(HorarioUsuario dto)
	{
		dto.setIdHorarioModified( false );
		dto.setNombreHorarioModified( false );
		dto.setIdEmpresaModified( false );
		dto.setIdEstatusModified( false );
	}

	/** 
	 * Returns all rows from the horario_usuario table that match the specified arbitrary SQL statement
	 */
	public HorarioUsuario[] findByDynamicSelect(String sql, Object[] sqlParams) throws HorarioUsuarioDaoException
	{
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		ResultSet rs = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			// construct the SQL statement
			final String SQL = sql;
		
		
			System.out.println( "Executing " + SQL );
			// prepare statement
			stmt = conn.prepareStatement( SQL );
			stmt.setMaxRows( maxRows );
		
			// bind parameters
			for (int i=0; sqlParams!=null && i<sqlParams.length; i++ ) {
				stmt.setObject( i+1, sqlParams[i] );
			}
		
		
			rs = stmt.executeQuery();
		
			// fetch the results
			return fetchMultiResults(rs);
		}
		catch (Exception _e) {
			_e.printStackTrace();
			throw new HorarioUsuarioDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(rs);
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

	/** 
	 * Returns all rows from the horario_usuario table that match the specified arbitrary SQL statement
	 */
	public HorarioUsuario[] findByDynamicWhere(String sql, Object[] sqlParams) throws HorarioUsuarioDaoException
	{
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		ResultSet rs = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			// construct the SQL statement
			final String SQL = SQL_SELECT + " WHERE " + sql;
		
		
			System.out.println( "Executing " + SQL );
			// prepare statement
			stmt = conn.prepareStatement( SQL );
			stmt.setMaxRows( maxRows );
		
			// bind parameters
			for (int i=0; sqlParams!=null && i<sqlParams.length; i++ ) {
				stmt.setObject( i+1, sqlParams[i] );
			}
		
		
			rs = stmt.executeQuery();
		
			// fetch the results
			return fetchMultiResults(rs);
		}
		catch (Exception _e) {
			_e.printStackTrace();
			throw new HorarioUsuarioDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(rs);
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

}
