/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.tsp.gespro.dao;

import java.util.Date;
import com.tsp.gespro.dto.*;
import com.tsp.gespro.exceptions.*;

public interface EmpleadoBitacoraPosicionDao
{
	/** 
	 * Inserts a new row in the empleado_bitacora_posicion table.
	 */
	public EmpleadoBitacoraPosicionPk insert(EmpleadoBitacoraPosicion dto) throws EmpleadoBitacoraPosicionDaoException;

	/** 
	 * Updates a single row in the empleado_bitacora_posicion table.
	 */
	public void update(EmpleadoBitacoraPosicionPk pk, EmpleadoBitacoraPosicion dto) throws EmpleadoBitacoraPosicionDaoException;

	/** 
	 * Deletes a single row in the empleado_bitacora_posicion table.
	 */
	public void delete(EmpleadoBitacoraPosicionPk pk) throws EmpleadoBitacoraPosicionDaoException;

	/** 
	 * Returns the rows from the empleado_bitacora_posicion table that matches the specified primary-key value.
	 */
	public EmpleadoBitacoraPosicion findByPrimaryKey(EmpleadoBitacoraPosicionPk pk) throws EmpleadoBitacoraPosicionDaoException;

	/** 
	 * Returns all rows from the empleado_bitacora_posicion table that match the criteria 'ID_BITACORA_POSICION = :idBitacoraPosicion'.
	 */
	public EmpleadoBitacoraPosicion findByPrimaryKey(long idBitacoraPosicion) throws EmpleadoBitacoraPosicionDaoException;

	/** 
	 * Returns all rows from the empleado_bitacora_posicion table that match the criteria ''.
	 */
	public EmpleadoBitacoraPosicion[] findAll() throws EmpleadoBitacoraPosicionDaoException;

	/** 
	 * Returns all rows from the empleado_bitacora_posicion table that match the criteria 'ID_BITACORA_POSICION = :idBitacoraPosicion'.
	 */
	public EmpleadoBitacoraPosicion[] findWhereIdBitacoraPosicionEquals(long idBitacoraPosicion) throws EmpleadoBitacoraPosicionDaoException;

	/** 
	 * Returns all rows from the empleado_bitacora_posicion table that match the criteria 'ID_USUARIO = :idUsuario'.
	 */
	public EmpleadoBitacoraPosicion[] findWhereIdUsuarioEquals(int idUsuario) throws EmpleadoBitacoraPosicionDaoException;

	/** 
	 * Returns all rows from the empleado_bitacora_posicion table that match the criteria 'LATITUD = :latitud'.
	 */
	public EmpleadoBitacoraPosicion[] findWhereLatitudEquals(double latitud) throws EmpleadoBitacoraPosicionDaoException;

	/** 
	 * Returns all rows from the empleado_bitacora_posicion table that match the criteria 'LONGITUD = :longitud'.
	 */
	public EmpleadoBitacoraPosicion[] findWhereLongitudEquals(double longitud) throws EmpleadoBitacoraPosicionDaoException;

	/** 
	 * Returns all rows from the empleado_bitacora_posicion table that match the criteria 'FECHA = :fecha'.
	 */
	public EmpleadoBitacoraPosicion[] findWhereFechaEquals(Date fecha) throws EmpleadoBitacoraPosicionDaoException;

	/** 
	 * Sets the value of maxRows
	 */
	public void setMaxRows(int maxRows);

	/** 
	 * Gets the value of maxRows
	 */
	public int getMaxRows();

	/** 
	 * Returns all rows from the empleado_bitacora_posicion table that match the specified arbitrary SQL statement
	 */
	public EmpleadoBitacoraPosicion[] findByDynamicSelect(String sql, Object[] sqlParams) throws EmpleadoBitacoraPosicionDaoException;

	/** 
	 * Returns all rows from the empleado_bitacora_posicion table that match the specified arbitrary SQL statement
	 */
	public EmpleadoBitacoraPosicion[] findByDynamicWhere(String sql, Object[] sqlParams) throws EmpleadoBitacoraPosicionDaoException;

}
