/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.tsp.gespro.dto;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

/** 
 * This class represents the primary key of the accion_bitacora table.
 */
public class AccionBitacoraPk implements Serializable
{
	protected long idBitacoraAccion;

	/** 
	 * This attribute represents whether the primitive attribute idBitacoraAccion is null.
	 */
	protected boolean idBitacoraAccionNull;

	/** 
	 * Sets the value of idBitacoraAccion
	 */
	public void setIdBitacoraAccion(long idBitacoraAccion)
	{
		this.idBitacoraAccion = idBitacoraAccion;
	}

	/** 
	 * Gets the value of idBitacoraAccion
	 */
	public long getIdBitacoraAccion()
	{
		return idBitacoraAccion;
	}

	/**
	 * Method 'AccionBitacoraPk'
	 * 
	 */
	public AccionBitacoraPk()
	{
	}

	/**
	 * Method 'AccionBitacoraPk'
	 * 
	 * @param idBitacoraAccion
	 */
	public AccionBitacoraPk(final long idBitacoraAccion)
	{
		this.idBitacoraAccion = idBitacoraAccion;
	}

	/** 
	 * Sets the value of idBitacoraAccionNull
	 */
	public void setIdBitacoraAccionNull(boolean idBitacoraAccionNull)
	{
		this.idBitacoraAccionNull = idBitacoraAccionNull;
	}

	/** 
	 * Gets the value of idBitacoraAccionNull
	 */
	public boolean isIdBitacoraAccionNull()
	{
		return idBitacoraAccionNull;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof AccionBitacoraPk)) {
			return false;
		}
		
		final AccionBitacoraPk _cast = (AccionBitacoraPk) _other;
		if (idBitacoraAccion != _cast.idBitacoraAccion) {
			return false;
		}
		
		if (idBitacoraAccionNull != _cast.idBitacoraAccionNull) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		_hashCode = 29 * _hashCode + (int) (idBitacoraAccion ^ (idBitacoraAccion >>> 32));
		_hashCode = 29 * _hashCode + (idBitacoraAccionNull ? 1 : 0);
		return _hashCode;
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "com.tsp.gespro.dto.AccionBitacoraPk: " );
		ret.append( "idBitacoraAccion=" + idBitacoraAccion );
		return ret.toString();
	}

}
