/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.tsp.gespro.dto;

import com.tsp.gespro.dao.*;
import com.tsp.gespro.factory.*;
import com.tsp.gespro.exceptions.*;
import java.io.Serializable;
import java.util.*;

public class DatosUsuario implements Serializable
{
	/** 
	 * This attribute maps to the column ID_DATOS_USUARIO in the datos_usuario table.
	 */
	protected int idDatosUsuario;

	/** 
	 * This attribute represents whether the attribute idDatosUsuario has been modified since being read from the database.
	 */
	protected boolean idDatosUsuarioModified = false;

	/** 
	 * This attribute maps to the column NOMBRE in the datos_usuario table.
	 */
	protected String nombre;

	/** 
	 * This attribute represents whether the attribute nombre has been modified since being read from the database.
	 */
	protected boolean nombreModified = false;

	/** 
	 * This attribute maps to the column APELLIDO_PAT in the datos_usuario table.
	 */
	protected String apellidoPat;

	/** 
	 * This attribute represents whether the attribute apellidoPat has been modified since being read from the database.
	 */
	protected boolean apellidoPatModified = false;

	/** 
	 * This attribute maps to the column APELLIDO_MAT in the datos_usuario table.
	 */
	protected String apellidoMat;

	/** 
	 * This attribute represents whether the attribute apellidoMat has been modified since being read from the database.
	 */
	protected boolean apellidoMatModified = false;

	/** 
	 * This attribute maps to the column DIRECCION in the datos_usuario table.
	 */
	protected String direccion;

	/** 
	 * This attribute represents whether the attribute direccion has been modified since being read from the database.
	 */
	protected boolean direccionModified = false;

	/** 
	 * This attribute maps to the column TELEFONO in the datos_usuario table.
	 */
	protected String telefono;

	/** 
	 * This attribute represents whether the attribute telefono has been modified since being read from the database.
	 */
	protected boolean telefonoModified = false;

	/** 
	 * This attribute maps to the column EXTENSION in the datos_usuario table.
	 */
	protected String extension;

	/** 
	 * This attribute represents whether the attribute extension has been modified since being read from the database.
	 */
	protected boolean extensionModified = false;

	/** 
	 * This attribute maps to the column CELULAR in the datos_usuario table.
	 */
	protected String celular;

	/** 
	 * This attribute represents whether the attribute celular has been modified since being read from the database.
	 */
	protected boolean celularModified = false;

	/** 
	 * This attribute maps to the column CORREO in the datos_usuario table.
	 */
	protected String correo;
        
        private String ciudad;
        protected boolean ciudadModified=false;

	/** 
	 * This attribute represents whether the attribute correo has been modified since being read from the database.
	 */
	protected boolean correoModified = false;

	/**
	 * Method 'DatosUsuario'
	 * 
	 */
	public DatosUsuario()
	{
	}

	/**
	 * Method 'getIdDatosUsuario'
	 * 
	 * @return int
	 */
	public int getIdDatosUsuario()
	{
		return idDatosUsuario;
	}

	/**
	 * Method 'setIdDatosUsuario'
	 * 
	 * @param idDatosUsuario
	 */
	public void setIdDatosUsuario(int idDatosUsuario)
	{
		this.idDatosUsuario = idDatosUsuario;
		this.idDatosUsuarioModified = true;
	}

	/** 
	 * Sets the value of idDatosUsuarioModified
	 */
	public void setIdDatosUsuarioModified(boolean idDatosUsuarioModified)
	{
		this.idDatosUsuarioModified = idDatosUsuarioModified;
	}

	/** 
	 * Gets the value of idDatosUsuarioModified
	 */
	public boolean isIdDatosUsuarioModified()
	{
		return idDatosUsuarioModified;
	}

	/**
	 * Method 'getNombre'
	 * 
	 * @return String
	 */
	public String getNombre()
	{
		return nombre;
	}

	/**
	 * Method 'getNombreCompleto'
	 * 
	 * @return String
	 */
	public String getNombreCompleto()
	{
		return nombre + " " + apellidoPat + "" + apellidoMat;
	}
        
	/**
	 * Method 'setNombre'
	 * 
	 * @param nombre
	 */
	public void setNombre(String nombre)
	{
		this.nombre = nombre;
		this.nombreModified = true;
	}

	/** 
	 * Sets the value of nombreModified
	 */
	public void setNombreModified(boolean nombreModified)
	{
		this.nombreModified = nombreModified;
	}

	/** 
	 * Gets the value of nombreModified
	 */
	public boolean isNombreModified()
	{
		return nombreModified;
	}

	/**
	 * Method 'getApellidoPat'
	 * 
	 * @return String
	 */
	public String getApellidoPat()
	{
		return apellidoPat;
	}

	/**
	 * Method 'setApellidoPat'
	 * 
	 * @param apellidoPat
	 */
	public void setApellidoPat(String apellidoPat)
	{
		this.apellidoPat = apellidoPat;
		this.apellidoPatModified = true;
	}

	/** 
	 * Sets the value of apellidoPatModified
	 */
	public void setApellidoPatModified(boolean apellidoPatModified)
	{
		this.apellidoPatModified = apellidoPatModified;
	}

	/** 
	 * Gets the value of apellidoPatModified
	 */
	public boolean isApellidoPatModified()
	{
		return apellidoPatModified;
	}

	/**
	 * Method 'getApellidoMat'
	 * 
	 * @return String
	 */
	public String getApellidoMat()
	{
		return apellidoMat;
	}

	/**
	 * Method 'setApellidoMat'
	 * 
	 * @param apellidoMat
	 */
	public void setApellidoMat(String apellidoMat)
	{
		this.apellidoMat = apellidoMat;
		this.apellidoMatModified = true;
	}

	/** 
	 * Sets the value of apellidoMatModified
	 */
	public void setApellidoMatModified(boolean apellidoMatModified)
	{
		this.apellidoMatModified = apellidoMatModified;
	}

	/** 
	 * Gets the value of apellidoMatModified
	 */
	public boolean isApellidoMatModified()
	{
		return apellidoMatModified;
	}

	/**
	 * Method 'getDireccion'
	 * 
	 * @return String
	 */
	public String getDireccion()
	{
		return direccion;
	}

	/**
	 * Method 'setDireccion'
	 * 
	 * @param direccion
	 */
	public void setDireccion(String direccion)
	{
		this.direccion = direccion;
		this.direccionModified = true;
	}

	/** 
	 * Sets the value of direccionModified
	 */
	public void setDireccionModified(boolean direccionModified)
	{
		this.direccionModified = direccionModified;
	}

	/** 
	 * Gets the value of direccionModified
	 */
	public boolean isDireccionModified()
	{
		return direccionModified;
	}

	/**
	 * Method 'getTelefono'
	 * 
	 * @return String
	 */
	public String getTelefono()
	{
		return telefono;
	}

	/**
	 * Method 'setTelefono'
	 * 
	 * @param telefono
	 */
	public void setTelefono(String telefono)
	{
		this.telefono = telefono;
		this.telefonoModified = true;
	}

	/** 
	 * Sets the value of telefonoModified
	 */
	public void setTelefonoModified(boolean telefonoModified)
	{
		this.telefonoModified = telefonoModified;
	}

	/** 
	 * Gets the value of telefonoModified
	 */
	public boolean isTelefonoModified()
	{
		return telefonoModified;
	}

	/**
	 * Method 'getExtension'
	 * 
	 * @return String
	 */
	public String getExtension()
	{
		return extension;
	}

	/**
	 * Method 'setExtension'
	 * 
	 * @param extension
	 */
	public void setExtension(String extension)
	{
		this.extension = extension;
		this.extensionModified = true;
	}

	/** 
	 * Sets the value of extensionModified
	 */
	public void setExtensionModified(boolean extensionModified)
	{
		this.extensionModified = extensionModified;
	}

	/** 
	 * Gets the value of extensionModified
	 */
	public boolean isExtensionModified()
	{
		return extensionModified;
	}

	/**
	 * Method 'getCelular'
	 * 
	 * @return String
	 */
	public String getCelular()
	{
		return celular;
	}

	/**
	 * Method 'setCelular'
	 * 
	 * @param celular
	 */
	public void setCelular(String celular)
	{
		this.celular = celular;
		this.celularModified = true;
	}

	/** 
	 * Sets the value of celularModified
	 */
	public void setCelularModified(boolean celularModified)
	{
		this.celularModified = celularModified;
	}

	/** 
	 * Gets the value of celularModified
	 */
	public boolean isCelularModified()
	{
		return celularModified;
	}

	/**
	 * Method 'getCorreo'
	 * 
	 * @return String
	 */
	public String getCorreo()
	{
		return correo;
	}

	/**
	 * Method 'setCorreo'
	 * 
	 * @param correo
	 */
	public void setCorreo(String correo)
	{
		this.correo = correo;
		this.correoModified = true;
	}

	/** 
	 * Sets the value of correoModified
	 */
	public void setCorreoModified(boolean correoModified)
	{
		this.correoModified = correoModified;
	}

	/** 
	 * Gets the value of correoModified
	 */
	public boolean isCorreoModified()
	{
		return correoModified;
	}
        
        /** 
	 * Sets the value of Ciudad
	 */
	public void setCiudadModified(boolean ciudadModified)
	{
		this.ciudadModified = ciudadModified;
	}

	/** 
	 * Gets the value of ciudadModified
	 */
	public boolean isCiudadModified()
	{
		return ciudadModified;
	}
        
        /**
        * @return the ciudad
        */
       public String getCiudad() {
           return ciudad;
       }

       /**
        * @param ciudad the ciudad to set
        */
       public void setCiudad(String ciudad) {
           this.ciudad = ciudad;
           this.ciudadModified = true;
       }
	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof DatosUsuario)) {
			return false;
		}
		
		final DatosUsuario _cast = (DatosUsuario) _other;
		if (idDatosUsuario != _cast.idDatosUsuario) {
			return false;
		}
		
		if (idDatosUsuarioModified != _cast.idDatosUsuarioModified) {
			return false;
		}
		
		if (nombre == null ? _cast.nombre != nombre : !nombre.equals( _cast.nombre )) {
			return false;
		}
		
		if (nombreModified != _cast.nombreModified) {
			return false;
		}
		
		if (apellidoPat == null ? _cast.apellidoPat != apellidoPat : !apellidoPat.equals( _cast.apellidoPat )) {
			return false;
		}
		
		if (apellidoPatModified != _cast.apellidoPatModified) {
			return false;
		}
		
		if (apellidoMat == null ? _cast.apellidoMat != apellidoMat : !apellidoMat.equals( _cast.apellidoMat )) {
			return false;
		}
		
		if (apellidoMatModified != _cast.apellidoMatModified) {
			return false;
		}
		
		if (direccion == null ? _cast.direccion != direccion : !direccion.equals( _cast.direccion )) {
			return false;
		}
		
		if (direccionModified != _cast.direccionModified) {
			return false;
		}
		
		if (telefono == null ? _cast.telefono != telefono : !telefono.equals( _cast.telefono )) {
			return false;
		}
		
		if (telefonoModified != _cast.telefonoModified) {
			return false;
		}
		
		if (extension == null ? _cast.extension != extension : !extension.equals( _cast.extension )) {
			return false;
		}
		
		if (extensionModified != _cast.extensionModified) {
			return false;
		}
		
		if (celular == null ? _cast.celular != celular : !celular.equals( _cast.celular )) {
			return false;
		}
		
		if (celularModified != _cast.celularModified) {
			return false;
		}
		
		if (correo == null ? _cast.correo != correo : !correo.equals( _cast.correo )) {
			return false;
		}
		
		if (correoModified != _cast.correoModified) {
			return false;
		}
                if (ciudad == null ? _cast.ciudad != ciudad : !ciudad.equals( _cast.ciudad )) {
			return false;
		}
		
		if (ciudadModified != _cast.ciudadModified) {
			return false;
		}
                
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		_hashCode = 29 * _hashCode + idDatosUsuario;
		_hashCode = 29 * _hashCode + (idDatosUsuarioModified ? 1 : 0);
		if (nombre != null) {
			_hashCode = 29 * _hashCode + nombre.hashCode();
		}
		
		_hashCode = 29 * _hashCode + (nombreModified ? 1 : 0);
		if (apellidoPat != null) {
			_hashCode = 29 * _hashCode + apellidoPat.hashCode();
		}
		
		_hashCode = 29 * _hashCode + (apellidoPatModified ? 1 : 0);
		if (apellidoMat != null) {
			_hashCode = 29 * _hashCode + apellidoMat.hashCode();
		}
		
		_hashCode = 29 * _hashCode + (apellidoMatModified ? 1 : 0);
		if (direccion != null) {
			_hashCode = 29 * _hashCode + direccion.hashCode();
		}
		
		_hashCode = 29 * _hashCode + (direccionModified ? 1 : 0);
		if (telefono != null) {
			_hashCode = 29 * _hashCode + telefono.hashCode();
		}
		
		_hashCode = 29 * _hashCode + (telefonoModified ? 1 : 0);
		if (extension != null) {
			_hashCode = 29 * _hashCode + extension.hashCode();
		}
		
		_hashCode = 29 * _hashCode + (extensionModified ? 1 : 0);
		if (celular != null) {
			_hashCode = 29 * _hashCode + celular.hashCode();
		}
		
		_hashCode = 29 * _hashCode + (celularModified ? 1 : 0);
		if (correo != null) {
			_hashCode = 29 * _hashCode + correo.hashCode();
		}
                _hashCode = 29 * _hashCode + (ciudadModified ? 1 : 0);
                if (ciudad != null) {
			_hashCode = 29 * _hashCode + ciudad.hashCode();
		}
		
		_hashCode = 29 * _hashCode + (correoModified ? 1 : 0);
		return _hashCode;
	}

	/**
	 * Method 'createPk'
	 * 
	 * @return DatosUsuarioPk
	 */
	public DatosUsuarioPk createPk()
	{
		return new DatosUsuarioPk(idDatosUsuario);
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "com.tsp.gespro.dto.DatosUsuario: " );
		ret.append( "idDatosUsuario=" + idDatosUsuario );
		ret.append( ", nombre=" + nombre );
		ret.append( ", apellidoPat=" + apellidoPat );
		ret.append( ", apellidoMat=" + apellidoMat );
		ret.append( ", direccion=" + direccion );
		ret.append( ", telefono=" + telefono );
		ret.append( ", extension=" + extension );
		ret.append( ", celular=" + celular );
		ret.append( ", correo=" + correo );
                ret.append( ", ciudad=" + ciudad );
		return ret.toString();
	}

   

}
