/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.tsp.gespro.dto;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

/** 
 * This class represents the primary key of the sgfens_estatus_pedido table.
 */
public class SgfensEstatusPedidoPk implements Serializable
{
	protected int idEstatusPedido;

	/** 
	 * This attribute represents whether the primitive attribute idEstatusPedido is null.
	 */
	protected boolean idEstatusPedidoNull;

	/** 
	 * Sets the value of idEstatusPedido
	 */
	public void setIdEstatusPedido(int idEstatusPedido)
	{
		this.idEstatusPedido = idEstatusPedido;
	}

	/** 
	 * Gets the value of idEstatusPedido
	 */
	public int getIdEstatusPedido()
	{
		return idEstatusPedido;
	}

	/**
	 * Method 'SgfensEstatusPedidoPk'
	 * 
	 */
	public SgfensEstatusPedidoPk()
	{
	}

	/**
	 * Method 'SgfensEstatusPedidoPk'
	 * 
	 * @param idEstatusPedido
	 */
	public SgfensEstatusPedidoPk(final int idEstatusPedido)
	{
		this.idEstatusPedido = idEstatusPedido;
	}

	/** 
	 * Sets the value of idEstatusPedidoNull
	 */
	public void setIdEstatusPedidoNull(boolean idEstatusPedidoNull)
	{
		this.idEstatusPedidoNull = idEstatusPedidoNull;
	}

	/** 
	 * Gets the value of idEstatusPedidoNull
	 */
	public boolean isIdEstatusPedidoNull()
	{
		return idEstatusPedidoNull;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof SgfensEstatusPedidoPk)) {
			return false;
		}
		
		final SgfensEstatusPedidoPk _cast = (SgfensEstatusPedidoPk) _other;
		if (idEstatusPedido != _cast.idEstatusPedido) {
			return false;
		}
		
		if (idEstatusPedidoNull != _cast.idEstatusPedidoNull) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		_hashCode = 29 * _hashCode + idEstatusPedido;
		_hashCode = 29 * _hashCode + (idEstatusPedidoNull ? 1 : 0);
		return _hashCode;
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "com.tsp.gespro.dto.SgfensEstatusPedidoPk: " );
		ret.append( "idEstatusPedido=" + idEstatusPedido );
		return ret.toString();
	}

}
