/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.tsp.gespro.dto;

import com.tsp.gespro.dao.*;
import com.tsp.gespro.factory.*;
import com.tsp.gespro.exceptions.*;
import java.io.Serializable;
import java.util.*;

public class Ubicacion implements Serializable
{
	/** 
	 * This attribute maps to the column ID_UBICACION in the ubicacion table.
	 */
	protected int idUbicacion;

	/** 
	 * This attribute represents whether the attribute idUbicacion has been modified since being read from the database.
	 */
	protected boolean idUbicacionModified = false;

	/** 
	 * This attribute maps to the column CALLE in the ubicacion table.
	 */
	protected String calle;

	/** 
	 * This attribute represents whether the attribute calle has been modified since being read from the database.
	 */
	protected boolean calleModified = false;

	/** 
	 * This attribute maps to the column NUM_INT in the ubicacion table.
	 */
	protected String numInt;

	/** 
	 * This attribute represents whether the attribute numInt has been modified since being read from the database.
	 */
	protected boolean numIntModified = false;

	/** 
	 * This attribute maps to the column NUM_EXT in the ubicacion table.
	 */
	protected String numExt;

	/** 
	 * This attribute represents whether the attribute numExt has been modified since being read from the database.
	 */
	protected boolean numExtModified = false;

	/** 
	 * This attribute maps to the column COLONIA in the ubicacion table.
	 */
	protected String colonia;

	/** 
	 * This attribute represents whether the attribute colonia has been modified since being read from the database.
	 */
	protected boolean coloniaModified = false;

	/** 
	 * This attribute maps to the column CODIGO_POSTAL in the ubicacion table.
	 */
	protected String codigoPostal;

	/** 
	 * This attribute represents whether the attribute codigoPostal has been modified since being read from the database.
	 */
	protected boolean codigoPostalModified = false;

	/** 
	 * This attribute maps to the column PAIS in the ubicacion table.
	 */
	protected String pais;

	/** 
	 * This attribute represents whether the attribute pais has been modified since being read from the database.
	 */
	protected boolean paisModified = false;

	/** 
	 * This attribute maps to the column ESTADO in the ubicacion table.
	 */
	protected String estado;

	/** 
	 * This attribute represents whether the attribute estado has been modified since being read from the database.
	 */
	protected boolean estadoModified = false;

	/** 
	 * This attribute maps to the column MUNICIPIO in the ubicacion table.
	 */
	protected String municipio;

	/** 
	 * This attribute represents whether the attribute municipio has been modified since being read from the database.
	 */
	protected boolean municipioModified = false;

	/**
	 * Method 'Ubicacion'
	 * 
	 */
	public Ubicacion()
	{
	}

	/**
	 * Method 'getIdUbicacion'
	 * 
	 * @return int
	 */
	public int getIdUbicacion()
	{
		return idUbicacion;
	}

	/**
	 * Method 'setIdUbicacion'
	 * 
	 * @param idUbicacion
	 */
	public void setIdUbicacion(int idUbicacion)
	{
		this.idUbicacion = idUbicacion;
		this.idUbicacionModified = true;
	}

	/** 
	 * Sets the value of idUbicacionModified
	 */
	public void setIdUbicacionModified(boolean idUbicacionModified)
	{
		this.idUbicacionModified = idUbicacionModified;
	}

	/** 
	 * Gets the value of idUbicacionModified
	 */
	public boolean isIdUbicacionModified()
	{
		return idUbicacionModified;
	}

	/**
	 * Method 'getCalle'
	 * 
	 * @return String
	 */
	public String getCalle()
	{
		return calle;
	}

	/**
	 * Method 'setCalle'
	 * 
	 * @param calle
	 */
	public void setCalle(String calle)
	{
		this.calle = calle;
		this.calleModified = true;
	}

	/** 
	 * Sets the value of calleModified
	 */
	public void setCalleModified(boolean calleModified)
	{
		this.calleModified = calleModified;
	}

	/** 
	 * Gets the value of calleModified
	 */
	public boolean isCalleModified()
	{
		return calleModified;
	}

	/**
	 * Method 'getNumInt'
	 * 
	 * @return String
	 */
	public String getNumInt()
	{
		return numInt;
	}

	/**
	 * Method 'setNumInt'
	 * 
	 * @param numInt
	 */
	public void setNumInt(String numInt)
	{
		this.numInt = numInt;
		this.numIntModified = true;
	}

	/** 
	 * Sets the value of numIntModified
	 */
	public void setNumIntModified(boolean numIntModified)
	{
		this.numIntModified = numIntModified;
	}

	/** 
	 * Gets the value of numIntModified
	 */
	public boolean isNumIntModified()
	{
		return numIntModified;
	}

	/**
	 * Method 'getNumExt'
	 * 
	 * @return String
	 */
	public String getNumExt()
	{
		return numExt;
	}

	/**
	 * Method 'setNumExt'
	 * 
	 * @param numExt
	 */
	public void setNumExt(String numExt)
	{
		this.numExt = numExt;
		this.numExtModified = true;
	}

	/** 
	 * Sets the value of numExtModified
	 */
	public void setNumExtModified(boolean numExtModified)
	{
		this.numExtModified = numExtModified;
	}

	/** 
	 * Gets the value of numExtModified
	 */
	public boolean isNumExtModified()
	{
		return numExtModified;
	}

	/**
	 * Method 'getColonia'
	 * 
	 * @return String
	 */
	public String getColonia()
	{
		return colonia;
	}

	/**
	 * Method 'setColonia'
	 * 
	 * @param colonia
	 */
	public void setColonia(String colonia)
	{
		this.colonia = colonia;
		this.coloniaModified = true;
	}

	/** 
	 * Sets the value of coloniaModified
	 */
	public void setColoniaModified(boolean coloniaModified)
	{
		this.coloniaModified = coloniaModified;
	}

	/** 
	 * Gets the value of coloniaModified
	 */
	public boolean isColoniaModified()
	{
		return coloniaModified;
	}

	/**
	 * Method 'getCodigoPostal'
	 * 
	 * @return String
	 */
	public String getCodigoPostal()
	{
		return codigoPostal;
	}

	/**
	 * Method 'setCodigoPostal'
	 * 
	 * @param codigoPostal
	 */
	public void setCodigoPostal(String codigoPostal)
	{
		this.codigoPostal = codigoPostal;
		this.codigoPostalModified = true;
	}

	/** 
	 * Sets the value of codigoPostalModified
	 */
	public void setCodigoPostalModified(boolean codigoPostalModified)
	{
		this.codigoPostalModified = codigoPostalModified;
	}

	/** 
	 * Gets the value of codigoPostalModified
	 */
	public boolean isCodigoPostalModified()
	{
		return codigoPostalModified;
	}

	/**
	 * Method 'getPais'
	 * 
	 * @return String
	 */
	public String getPais()
	{
		return pais;
	}

	/**
	 * Method 'setPais'
	 * 
	 * @param pais
	 */
	public void setPais(String pais)
	{
		this.pais = pais;
		this.paisModified = true;
	}

	/** 
	 * Sets the value of paisModified
	 */
	public void setPaisModified(boolean paisModified)
	{
		this.paisModified = paisModified;
	}

	/** 
	 * Gets the value of paisModified
	 */
	public boolean isPaisModified()
	{
		return paisModified;
	}

	/**
	 * Method 'getEstado'
	 * 
	 * @return String
	 */
	public String getEstado()
	{
		return estado;
	}

	/**
	 * Method 'setEstado'
	 * 
	 * @param estado
	 */
	public void setEstado(String estado)
	{
		this.estado = estado;
		this.estadoModified = true;
	}

	/** 
	 * Sets the value of estadoModified
	 */
	public void setEstadoModified(boolean estadoModified)
	{
		this.estadoModified = estadoModified;
	}

	/** 
	 * Gets the value of estadoModified
	 */
	public boolean isEstadoModified()
	{
		return estadoModified;
	}

	/**
	 * Method 'getMunicipio'
	 * 
	 * @return String
	 */
	public String getMunicipio()
	{
		return municipio;
	}

	/**
	 * Method 'setMunicipio'
	 * 
	 * @param municipio
	 */
	public void setMunicipio(String municipio)
	{
		this.municipio = municipio;
		this.municipioModified = true;
	}

	/** 
	 * Sets the value of municipioModified
	 */
	public void setMunicipioModified(boolean municipioModified)
	{
		this.municipioModified = municipioModified;
	}

	/** 
	 * Gets the value of municipioModified
	 */
	public boolean isMunicipioModified()
	{
		return municipioModified;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof Ubicacion)) {
			return false;
		}
		
		final Ubicacion _cast = (Ubicacion) _other;
		if (idUbicacion != _cast.idUbicacion) {
			return false;
		}
		
		if (idUbicacionModified != _cast.idUbicacionModified) {
			return false;
		}
		
		if (calle == null ? _cast.calle != calle : !calle.equals( _cast.calle )) {
			return false;
		}
		
		if (calleModified != _cast.calleModified) {
			return false;
		}
		
		if (numInt == null ? _cast.numInt != numInt : !numInt.equals( _cast.numInt )) {
			return false;
		}
		
		if (numIntModified != _cast.numIntModified) {
			return false;
		}
		
		if (numExt == null ? _cast.numExt != numExt : !numExt.equals( _cast.numExt )) {
			return false;
		}
		
		if (numExtModified != _cast.numExtModified) {
			return false;
		}
		
		if (colonia == null ? _cast.colonia != colonia : !colonia.equals( _cast.colonia )) {
			return false;
		}
		
		if (coloniaModified != _cast.coloniaModified) {
			return false;
		}
		
		if (codigoPostal == null ? _cast.codigoPostal != codigoPostal : !codigoPostal.equals( _cast.codigoPostal )) {
			return false;
		}
		
		if (codigoPostalModified != _cast.codigoPostalModified) {
			return false;
		}
		
		if (pais == null ? _cast.pais != pais : !pais.equals( _cast.pais )) {
			return false;
		}
		
		if (paisModified != _cast.paisModified) {
			return false;
		}
		
		if (estado == null ? _cast.estado != estado : !estado.equals( _cast.estado )) {
			return false;
		}
		
		if (estadoModified != _cast.estadoModified) {
			return false;
		}
		
		if (municipio == null ? _cast.municipio != municipio : !municipio.equals( _cast.municipio )) {
			return false;
		}
		
		if (municipioModified != _cast.municipioModified) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		_hashCode = 29 * _hashCode + idUbicacion;
		_hashCode = 29 * _hashCode + (idUbicacionModified ? 1 : 0);
		if (calle != null) {
			_hashCode = 29 * _hashCode + calle.hashCode();
		}
		
		_hashCode = 29 * _hashCode + (calleModified ? 1 : 0);
		if (numInt != null) {
			_hashCode = 29 * _hashCode + numInt.hashCode();
		}
		
		_hashCode = 29 * _hashCode + (numIntModified ? 1 : 0);
		if (numExt != null) {
			_hashCode = 29 * _hashCode + numExt.hashCode();
		}
		
		_hashCode = 29 * _hashCode + (numExtModified ? 1 : 0);
		if (colonia != null) {
			_hashCode = 29 * _hashCode + colonia.hashCode();
		}
		
		_hashCode = 29 * _hashCode + (coloniaModified ? 1 : 0);
		if (codigoPostal != null) {
			_hashCode = 29 * _hashCode + codigoPostal.hashCode();
		}
		
		_hashCode = 29 * _hashCode + (codigoPostalModified ? 1 : 0);
		if (pais != null) {
			_hashCode = 29 * _hashCode + pais.hashCode();
		}
		
		_hashCode = 29 * _hashCode + (paisModified ? 1 : 0);
		if (estado != null) {
			_hashCode = 29 * _hashCode + estado.hashCode();
		}
		
		_hashCode = 29 * _hashCode + (estadoModified ? 1 : 0);
		if (municipio != null) {
			_hashCode = 29 * _hashCode + municipio.hashCode();
		}
		
		_hashCode = 29 * _hashCode + (municipioModified ? 1 : 0);
		return _hashCode;
	}

	/**
	 * Method 'createPk'
	 * 
	 * @return UbicacionPk
	 */
	public UbicacionPk createPk()
	{
		return new UbicacionPk(idUbicacion);
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "com.tsp.gespro.dto.Ubicacion: " );
		ret.append( "idUbicacion=" + idUbicacion );
		ret.append( ", calle=" + calle );
		ret.append( ", numInt=" + numInt );
		ret.append( ", numExt=" + numExt );
		ret.append( ", colonia=" + colonia );
		ret.append( ", codigoPostal=" + codigoPostal );
		ret.append( ", pais=" + pais );
		ret.append( ", estado=" + estado );
		ret.append( ", municipio=" + municipio );
		return ret.toString();
	}

}
