/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.tsp.gespro.dto;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

/** 
 * This class represents the primary key of the usuarios table.
 */
public class UsuariosPk implements Serializable
{
	protected int idUsuarios;

	/** 
	 * This attribute represents whether the primitive attribute idUsuarios is null.
	 */
	protected boolean idUsuariosNull;

	/** 
	 * Sets the value of idUsuarios
	 */
	public void setIdUsuarios(int idUsuarios)
	{
		this.idUsuarios = idUsuarios;
	}

	/** 
	 * Gets the value of idUsuarios
	 */
	public int getIdUsuarios()
	{
		return idUsuarios;
	}

	/**
	 * Method 'UsuariosPk'
	 * 
	 */
	public UsuariosPk()
	{
	}

	/**
	 * Method 'UsuariosPk'
	 * 
	 * @param idUsuarios
	 */
	public UsuariosPk(final int idUsuarios)
	{
		this.idUsuarios = idUsuarios;
	}

	/** 
	 * Sets the value of idUsuariosNull
	 */
	public void setIdUsuariosNull(boolean idUsuariosNull)
	{
		this.idUsuariosNull = idUsuariosNull;
	}

	/** 
	 * Gets the value of idUsuariosNull
	 */
	public boolean isIdUsuariosNull()
	{
		return idUsuariosNull;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof UsuariosPk)) {
			return false;
		}
		
		final UsuariosPk _cast = (UsuariosPk) _other;
		if (idUsuarios != _cast.idUsuarios) {
			return false;
		}
		
		if (idUsuariosNull != _cast.idUsuariosNull) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		_hashCode = 29 * _hashCode + idUsuarios;
		_hashCode = 29 * _hashCode + (idUsuariosNull ? 1 : 0);
		return _hashCode;
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "com.tsp.gespro.dto.UsuariosPk: " );
		ret.append( "idUsuarios=" + idUsuarios );
		return ret.toString();
	}

}
