/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.tsp.gespro.dao;

import com.tsp.gespro.dto.*;
import com.tsp.gespro.exceptions.*;

public interface SgfensEstatusPedidoDao
{
	/** 
	 * Inserts a new row in the sgfens_estatus_pedido table.
	 */
	public SgfensEstatusPedidoPk insert(SgfensEstatusPedido dto) throws SgfensEstatusPedidoDaoException;

	/** 
	 * Updates a single row in the sgfens_estatus_pedido table.
	 */
	public void update(SgfensEstatusPedidoPk pk, SgfensEstatusPedido dto) throws SgfensEstatusPedidoDaoException;

	/** 
	 * Deletes a single row in the sgfens_estatus_pedido table.
	 */
	public void delete(SgfensEstatusPedidoPk pk) throws SgfensEstatusPedidoDaoException;

	/** 
	 * Returns the rows from the sgfens_estatus_pedido table that matches the specified primary-key value.
	 */
	public SgfensEstatusPedido findByPrimaryKey(SgfensEstatusPedidoPk pk) throws SgfensEstatusPedidoDaoException;

	/** 
	 * Returns all rows from the sgfens_estatus_pedido table that match the criteria 'ID_ESTATUS_PEDIDO = :idEstatusPedido'.
	 */
	public SgfensEstatusPedido findByPrimaryKey(int idEstatusPedido) throws SgfensEstatusPedidoDaoException;

	/** 
	 * Returns all rows from the sgfens_estatus_pedido table that match the criteria ''.
	 */
	public SgfensEstatusPedido[] findAll() throws SgfensEstatusPedidoDaoException;

	/** 
	 * Returns all rows from the sgfens_estatus_pedido table that match the criteria 'ID_ESTATUS_PEDIDO = :idEstatusPedido'.
	 */
	public SgfensEstatusPedido[] findWhereIdEstatusPedidoEquals(int idEstatusPedido) throws SgfensEstatusPedidoDaoException;

	/** 
	 * Returns all rows from the sgfens_estatus_pedido table that match the criteria 'NOMBRE = :nombre'.
	 */
	public SgfensEstatusPedido[] findWhereNombreEquals(String nombre) throws SgfensEstatusPedidoDaoException;

	/** 
	 * Returns all rows from the sgfens_estatus_pedido table that match the criteria 'DESCRIPCION = :descripcion'.
	 */
	public SgfensEstatusPedido[] findWhereDescripcionEquals(String descripcion) throws SgfensEstatusPedidoDaoException;

	/** 
	 * Sets the value of maxRows
	 */
	public void setMaxRows(int maxRows);

	/** 
	 * Gets the value of maxRows
	 */
	public int getMaxRows();

	/** 
	 * Returns all rows from the sgfens_estatus_pedido table that match the specified arbitrary SQL statement
	 */
	public SgfensEstatusPedido[] findByDynamicSelect(String sql, Object[] sqlParams) throws SgfensEstatusPedidoDaoException;

	/** 
	 * Returns all rows from the sgfens_estatus_pedido table that match the specified arbitrary SQL statement
	 */
	public SgfensEstatusPedido[] findByDynamicWhere(String sql, Object[] sqlParams) throws SgfensEstatusPedidoDaoException;

}
